name: llama-factory-nvidia
services:
  llama-factory-nvidia:
    image: hiyouga/llamafactory:0.9.4
    container_name: llama-factory-nvidia
    ports:
    - target: 7860
      published: '18877'
      protocol: tcp
    tty: true
    stdin_open: true
    command:
    - llamafactory-cli
    - webui
    deploy:
      resources:
        reservations:
          memory: 6G
          devices:
          - driver: nvidia
            count: all
            capabilities:
            - gpu
    restart: unless-stopped
x-casaos:
  app_id: org.icewhale.llamafactorynvidia
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.llamafactorynvidia/assets/icon.svg
  title:
    de_DE: LLaMA Factory(Nvidia GPU)
    el_GR: LLaMA Factory(Nvidia GPU)
    en_GB: LLaMA Factory(Nvidia GPU)
    en_US: LLaMA Factory(Nvidia GPU)
    fr_FR: LLaMA Factory(Nvidia GPU)
    hr_HR: LLaMA Factory(Nvidia GPU)
    it_IT: LLaMA Factory(Nvidia GPU)
    ja_JP: LLaMA Factory(Nvidia GPU)
    ko_KR: LLaMA Factory(Nvidia GPU)
    nb_NO: LLaMA Factory(Nvidia GPU)
    pt_PT: LLaMA Factory(Nvidia GPU)
    ru_RU: LLaMA Factory(Nvidia GPU)
    sv_SE: LLaMA Factory(Nvidia GPU)
    tr_TR: LLaMA Factory(Nvidia GPU)
    zh_CN: LLaMA Factory(Nvidia GPU)
  index: /
  scheme: http
  main: llama-factory-nvidia
  port_map: '18877'
  version: 0.9.4
