name: overseerr
services:
  overseerr:
    image: linuxserver/overseerr@sha256:6108ed066d4a919c05251d9dab041c1e55e67ff7247e7b31be97b65ffcbaeeb1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
    - target: 5055
      published: 5055
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/overseerr/config
      target: /config
    container_name: overseerr
x-casaos:
  app_id: org.icewhale.overseerr
  main: overseerr
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/overseerr/assets/icon.svg
  title:
    en_US: Overseerr
  port_map: '5055'
  version: 1.35.0
