name: deluge
services:
  deluge:
    environment:
      DELUGE_LOGLEVEL: error
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: linuxserver/deluge:2.2.0@sha256:c240d1f0c1a3c4e0c8118895c964c96cf31cb3a797a32aa381ab6873498cbae7
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
    - target: 8112
      published: '8112'
      protocol: tcp
    - target: 6881
      published: '6881'
      protocol: tcp
    - target: 6881
      published: '6881'
      protocol: udp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /config
    - type: bind
      source: /DATA
      target: /DATA
    container_name: deluge
x-casaos:
  id: org.icewhale.deluge
  main: deluge
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.deluge/assets/icon.svg
  title:
    en_US: Deluge
  index: /
  port_map: '8112'
  version: 2.2.0
