name: grafana
services:
  grafana:
    image: grafana/grafana:13.0.1-security-01@sha256:135f4b96b7a54f904415dc51e71a1cd945b1f8400772b2feac2df5112b43f4ed
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 3000
      published: '3003'
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /var/lib/grafana
    container_name: grafana
x-casaos:
  id: org.icewhale.grafana
  main: grafana
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.grafana/assets/icon.svg
  title:
    en_US: Grafana
  index: /
  port_map: '3003'
  version: 13.0.1-security-01
