name: twingate-connector
services:
  twingate-connector:
    image: twingate/connector:1@sha256:b5fb0e5ac512f0127537d597dc207367be70eedf7e16ef271ea79e905c6be2d3
    container_name: twingate-connector
    command:
      - /connectord
    environment:
      TWINGATE_NETWORK: ""
      TWINGATE_ACCESS_TOKEN: ""
      TWINGATE_REFRESH_TOKEN: ""
      TWINGATE_LABEL_HOSTNAME: ${HOSTNAME}

    restart: unless-stopped
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
    network_mode: default
    privileged: false
    cpu_shares: 90
    deploy:
      resources:
        reservations:
          memory: 500M  # Modify as needed since the original command didn't specify memory reservation

x-casaos:
  id: org.icewhale.twingateconnector
  main: twingate-connector
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.twingateconnector/assets/icon.svg
  title:
    en_US: Twingate
  index: /
  port_map: ""
  version: "1.0.0"
