name: myspeed
services:
  myspeed:
    container_name: myspeed
    deploy:
      resources:
        limits:
          memory: 256M
    image: germannewsmaker/myspeed:1.0.9@sha256:3fbf1e2908079dbd10651c2b4f9550c4163a0d6e42110dd395a19cf3f8063879
    ports:
    - target: 5216
      published: '5216'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /myspeed/data
    network_mode: bridge
    privileged: false
x-casaos:
  id: org.icewhale.myspeed
  main: myspeed
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.myspeed/assets/icon.svg
  title:
    en_US: MySpeed
    pt_BR: MySpeed
  index: /
  port_map: '5216'
  version: 1.0.9
