name: adminer
services:
  adminer:
    image: adminer:5.4.2@sha256:a897f24da9af68f2b0d5092dba067efeefe5bd979ee090bb7eb0adc8d73a82ff
    deploy:
      resources:
        reservations:
          memory: 32M
    restart: unless-stopped
    ports:
    - 8080:8080
    container_name: adminer
x-casaos:
  id: org.icewhale.adminer
  main: adminer
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.adminer/assets/icon.svg
  title:
    en_US: Adminer
  port_map: '8080'
  version: 5.4.2
