name: stable-diffusion-webui
services:
  stable-diffusion-webui:
    image: johnguan/stable-diffusion-webui:latest
    runtime: nvidia
    ipc: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          memory: 12G
    network_mode: bridge
    ports:
      - target: 7860
        published: "7860"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Stable-Diffusion-WebUI/models
        target: /data/models
      - type: bind
        source: /DATA/AppData/Stable-Diffusion-WebUI/outputs
        target: /data/outputs
      - type: bind
        source: /DATA/AppData/Stable-Diffusion-WebUI/config
        target: /data/config
    privileged: false
    container_name: stable-diffusion-webui
x-casaos:
  architectures:
    - amd64
  main: stable-diffusion-webui
  author: JohnGuan
  category: Developer
  description:
    en_us: Stable Diffusion WebUI is a browser interface for Stable Diffusion, an AI model that can generate images from text prompts or modify existing images with text prompts.
    zh_cn: Stable Diffusion WebUI是Stable Diffusion的浏览器界面，Stable Diffusion是一个AI模型，可以从文本提示中生成图像或使用文本提示修改现有图像。
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Stable-Diffusion-WebUI/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Stable-Diffusion-WebUI/screenshot-1.png
  tagline:
    en_us: Stable Diffusion web UI is a great way to explore the possibilities of Stable Diffusion and create amazing images with just a few clicks.
    zh_cn: Stable Diffusion web UI是探索Stable Diffusion可能性并仅通过几次点击创建惊人图像的绝佳方式。
  scheme: http
  store_app_id: stable-diffusion-webui
  title:
    en_us: Stable Diffusion WebUI
  index: /
  port_map: "7860"

