name: resilio-sync
services:
  resilio-sync:
    environment:
    - PGID=$PGID
    - PUID=$PUID
    - TZ=$TZ
    image: linuxserver/resilio-sync@sha256:9486ead71c79bf283e9d08afbfe6711d6646cab501931d72f8678811f2c5be58
    network_mode: bridge
    ports:
    - target: 55555
      published: '55555'
      protocol: tcp
    - target: 8888
      published: '8888'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /sync
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /config
    - type: bind
      source: /DATA/Downloads
      target: /downloads
    privileged: false
    container_name: resilio-sync
x-casaos:
  app_id: org.icewhale.resiliosync
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/resilio-sync/assets/icon.svg
  index: /
  port_map: '8888'
  scheme: http
  title:
    en_US: resilio-sync
  version: 3.1.2
