---
name: stash
services:
  app:
    image: stashapp/stash:v0.21.0
    restart: unless-stopped
    environment:
      - TZ=$TZ
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_BLOBS=/blobs/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PLUGINS=/plugins/
      - STASH_THEMES=/themes/
      - STASH_USERSCRIPTS=/userscripts/
      - STASH_VALIDATOR=/validator/
      - STASH_SCRAPERS=/scrapers/
      - STASH_TEMPLATES=/templates/
      - STASH_CUSTOM_PERFORMERS=/custom_performers/
      - STASH_BACKUPS=/backups/
      - STASH_CONFIG_FILE=/config/config.yml
      - STASH_LOG_FILE=/logs/stash.log
    x-casaos:
      envs:
        - container: STASH_STASH
          description:
            en_us: Stash Stash
        - container: STASH_GENERATED
          description:
            en_us: Stash Generated
        - container: STASH_METADATA
          description:
            en_us: Stash Metadata
        - container: STASH_BLOBS
          description:
            en_us: Stash Blobs
        - container: STASH_CACHE
          description:
            en_us: Stash Cache
        - container: STASH_PLUGINS
          description:
            en_us: Stash Plugins
        - container: STASH_THEMES
          description:
            en_us: Stash Themes
        - container: STASH_USERSCRIPTS
          description:
            en_us: Stash Userscripts
        - container: STASH_VALIDATOR
          description:
            en_us: Stash Validator
        - container: STASH_SCRAPERS
          description:
            en_us: Stash Scrapers
        - container: STASH_TEMPLATES
          description:
            en_us: Stash Templates
        - container: STASH_CUSTOM_PERFORMERS
          description:
            en_us: Stash Custom Performers
        - container: STASH_BACKUPS
          description:
            en_us: Stash Backups
        - container: STASH_CONFIG_FILE
          description:
            en_us: Stash Config File
        - container: STASH_LOG_FILE
          description:
            en_us: Stash Log File
      volumes:
        - container: /data
          description:
            en_us: Stash Stash
        - container: /media
          description:
            en_us: Stash Media
      ports:
        - container: "9999"
          host: "9999"
          description:
            en_us: Stash Web Port
    ports:
      - 9999:9999
    volumes:
      - /DATA/AppData/$AppID/backups:/backups
      - /DATA/AppData/$AppID/blobs:/blobs
      - /DATA/AppData/$AppID/cache:/cache
      - /DATA/AppData/$AppID/config:/config
      - /DATA/AppData/$AppID/custom_performers:/custom_performers
      - /DATA/AppData/$AppID/data:/data
      - /DATA/AppData/$AppID/generated:/generated
      - /DATA/AppData/$AppID/logs:/logs
      - /DATA/AppData/$AppID/metadata:/metadata
      - /DATA/AppData/$AppID/plugins:/plugins
      - /DATA/AppData/$AppID/scrapers:/scrapers
      - /DATA/AppData/$AppID/templates:/templates
      - /DATA/AppData/$AppID/themes:/themes
      - /DATA/AppData/$AppID/userscripts:/userscripts
      - /DATA/AppData/$AppID/validator:/validator
      - /DATA/Media/xxx:/media
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  author: f4bio
  description:
    en_us: "Stash allows you to organize and view your own collection of adult video and image files. Think of it like a private PornHub site for your personal porn collection. Documentation: https://docs.stashapp.cc"
  tagline:
    en_us: "An organizer for your porn, written in Go"
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Stash/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Stash/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Stash/screenshot-3.jpg
  developer: Stash
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@develop/Apps/Stash/icon.png
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@develop/Apps/Stash/thumbnail.jpg
  title:
    en_us: Stash
  category: Utilities
  port_map: "9999"
