name: ddns-go
services:
  ddns-go:
    image: jeessy/ddns-go@sha256:7fdf2ac701261dd4bace2e4dbee1db77ae4f9c98453690108adac9794fe68547
    network_mode: bridge
    deploy:
      resources:
        reservations:
          memory: 32M
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /root
    ports:
    - target: 9876
      published: '9876'
      protocol: tcp
    container_name: ddns-go
x-casaos:
  app_id: org.icewhale.ddnsgo
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/ddns-go/assets/icon.svg
  main: ddns-go
  port_map: '9876'
  scheme: http
  title:
    en_US: ddns-go
  version: 6.17.1
