name: komga
services:
  komga:
    image: gotson/komga@sha256:dae630271561b642d47c9723803ec77900d1f0a803fbe6a42da69db5b21ebaeb
    container_name: komga
    deploy:
      resources:
        reservations:
          memory: 128M
    network_mode: bridge
    ports:
    - target: 25600
      published: '25600'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /config
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /data
    - type: bind
      source: /etc/timezone
      target: /etc/timezone
    environment:
      PGID: '1000'
      PUID: '1000'
x-casaos:
  app_id: org.icewhale.komga
  main: komga
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/komga/assets/icon.svg
  scheme: http
  port_map: '25600'
  index: /
  title:
    en_US: Komga
  version: 1.24.4
