name: retroarch
services:
  retroarch:
    image: inglebard/retroarch-web:latest
    container_name: retroarch
    deploy:
      resources:
        reservations:
          memory: 64M
    restart: unless-stopped
    environment:
    - ROOT_WWW_PATH="/var/www/html"
    ports:
    - 8183:80
x-casaos:
  app_id: org.icewhale.retroarch
  main: retroarch
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.retroarch/assets/icon.svg
  scheme: http
  port_map: '8183'
  index: /
  title:
    en_US: RetroArch
  version: 0.0.1
