name: beaverhabittracker
services:
  beaverhabittracker:
    image: daya0576/beaverhabits:0.9.1
    container_name: beaverhabittracker
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M
    restart: unless-stopped
    user: 1000:1000
    ports:
    - target: 8080
      published: '15580'
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/
      target: /app/.user
    environment:
      HABITS_STORAGE: USER_DISK
      TRUSTED_LOCAL_EMAIL: your@email.com
      INDEX_HABIT_DATE_COLUMNS: 5
      ENABLE_IOS_STANDALONE: true
x-casaos:
  app_id: org.icewhale.beaverhabittracker
  main: beaverhabittracker
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/beaverhabittracker/assets/icon.svg
  scheme: http
  port_map: '15580'
  index: /
  title:
    en_US: BeaverHabitTracker
  version: 0.9.1
