name: rdtclient
services:
  rdtclient:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
      UMASK: "002"
    cpu_shares: 50
    command: []
    container_name: rdtclient
    deploy:
      resources:
        reservations:
          memory: 64M
    image: rogerfar/rdtclient:2.0.136
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/RDTClient/icon.svg
    ports:
      - target: 6500
        published: "6500"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/Downloads
        target: /data/downloads
      - type: bind
        source: /DATA/AppData/$AppID/db
        target: /data/db
    network_mode: bridge
    privileged: false
x-casaos:
  app_id: org.icewhale.rdtclient
  architectures:                  # a list of architectures that the app supports
      - amd64
      - arm
      - arm64
  author: calganaygun
  category: Media
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/RDTClient/icon.svg
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/RDTClient/screenshot-1.png
  index: /
  port_map: "6500"
  scheme: http
  store_app_id: rdtclient
  title:
    en_US: Real-Debrid Torrent Client
  version: "2.0.136"
  update_at: "2026-05-30"
  release_notes: "RDTClient v2.0.136 adds a devcontainer development workflow and upgrades the torbox.net dependency."
  website: ""
  repo: "https://github.com/rogerfar/rdt-client"
  support: "https://github.com/rogerfar/rdt-client/issues"
  docs: "https://github.com/rogerfar/rdt-client/wiki"
