name: excalidraw
services:
  excalidraw:
    image: excalidraw/excalidraw@sha256:f7ee194addd607bf831d2af0f0a34463dd4225e426cf35199ef0b12a803398e9
    container_name: excalidraw
    deploy:
      resources:
        reservations:
          memory: 256M
    restart: unless-stopped
    ports:
    - target: 80
      published: '17638'
      protocol: tcp
x-casaos:
  app_id: org.icewhale.excalidraw
  main: excalidraw
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/excalidraw/assets/icon.svg
  scheme: http
  port_map: '17638'
  index: /
  title:
    en_US: Excalidraw
  version: 0.18.1
