name: anaconda3
services:
  anaconda3:
    container_name: anaconda3
    image: continuumio/anaconda3:2024.10-1@sha256:4ee8bf6535e43ad8c131fcd145b0b51fc2862ac5ad77f15d96559d8f56dc77e4
    network_mode: bridge
    restart: unless-stopped
    environment:
    - LANG=C.UTF-8
    - LC_ALL=C.UTF-8
    - PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
    - target: 8888
      published: '8888'
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/notebooks
      target: /opt/notebooks
    command:
    - /bin/bash
    - -c
    - conda install -c conda-forge jupyterlab -y --quiet && jupyter lab --notebook-dir=/opt/notebooks
      --ip='*' --port=8888 --no-browser --allow-root
x-casaos:
  id: org.icewhale.anaconda3
  main: anaconda3
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.anaconda3/assets/icon.svg
  scheme: http
  port_map: '8888'
  index: /
  title:
    en_US: Anaconda3
  version: 2024.10.0-1
