name: adminer
services:
  adminer:
    image: adminer@sha256:4dae499420bb9ba8c5d73745e5c8e02b696acd214b66b5f2946eceee7f171fee
    deploy:
      resources:
        reservations:
          memory: 32M
    restart: unless-stopped
    ports:
    - 8080:8080
    container_name: adminer
x-casaos:
  app_id: org.icewhale.adminer
  main: adminer
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/adminer/assets/icon.svg
  title:
    en_US: Adminer
  port_map: '8080'
  version: 5.4.2
