name: adminer
services:
  adminer:
    image: adminer:4.8.1
    deploy:
      resources:
        reservations:
          memory: 32M
    restart: unless-stopped
    ports:
      - 8080:8080
    x-casaos:
      ports:
        - container: "8080"
          description:
            en_us: Adminer HTTP Port
            zh_cn: Adminer HTTP 端口
    container_name: adminer
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: adminer
  author: Tim Düsterhus
  category: Database
  description:
    en_us: Adminer (formerly phpMinAdmin) is a full-featured database management tool written in PHP. Conversely to phpMyAdmin, it consist of a single file ready to deploy to the target server. Adminer is available for MySQL, PostgreSQL, SQLite, MS SQL, Oracle, Firebird, SimpleDB, Elasticsearch and MongoDB.
    zh_cn: Adminer（前身为phpMinAdmin）是一个用PHP编写的功能齐全的数据库管理工具。区别于phpMyAdmin，它仅为单个部署到目标服务器的文件（轻量）。Adminer可用于MySQL、PostgreSQL、SQLite、MS SQL、Oracle、Firebird、SimpleDB、Elasticsearch和MongoDB。
  developer: Jakub Vrána
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Adminer/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Adminer/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Adminer/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Adminer/screenshot-3.png
  tagline:
    en_us: Database management in a single PHP file
    zh_cn: 单PHP文件的数据库管理工具
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Adminer/thumbnail.png
  title:
    en_us: Adminer
  port_map: '8080'
