name: vaultwarden
services:
  vaultwarden:
    image: vaultwarden/server:1.32.7
    deploy:
      resources:
        reservations:
          memory: "256M"
    network_mode: bridge
    ports:
      - target: 80
        published: "10380"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
    x-casaos:
      ports:
        - container: "80"
          description:
            en_us: WebUI HTTP Port
            zh_cn: WebUI HTTP 端口

      volumes:
        - container: /data
          description:
            en_us: Vaultwarden data directory.
            zh_cn: Vaultwarden 数据目录。
    container_name: vaultwarden
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: vaultwarden
  author: CasaOS Team
  category: Utilities
  description:
    en_us: Alternative implementation of the Bitwarden server API written in Rust and compatible with upstream Bitwarden clients*, perfect for self-hosted deployment where running the official resource-heavy service might not be ideal.
    zh_cn: 用 Rust 编写的 Bitwarden 服务器 API 的替代实现，与上游 Bitwarden 客户端兼容，适合自托管部署，其中运行官方资源密集型服务可能不是理想的选择。
    ar_sa: تنفيذ بديل لواجهة برمجة تطبيقات Bitwarden الخادم بلغة Rust وتوافقه مع عملاء Bitwarden الرئيسيين ، مثالي للتشغيل المستقل حيث قد لا يكون تشغيل الخدمة الرسومية الرسمية الموارد المثالية.
    de_de: Alternative Implementierung der Bitwarden-Server-API in Rust und kompatibel mit den Upstream-Bitwarden-Clients *, perfekt für die selbst gehostete Bereitstellung, bei der die Ausführung des offiziellen ressourcenintensiven Dienstes nicht ideal sein könnte.
    es_es: Implementación alternativa de la API del servidor Bitwarden escrita en Rust y compatible con los clientes Bitwarden superiores *, perfecta para la implementación autohospedada donde la ejecución del servicio oficial pesado en recursos puede no ser ideal.
    fr_fr: Implémentation alternative de l'API du serveur Bitwarden écrite en Rust et compatible avec les clients Bitwarden supérieurs *, parfaite pour le déploiement auto-hébergé où l'exécution du service officiel lourd en ressources peut ne pas être idéale.
    hu_hu: Rust nyelven írt Bitwarden szerver API alternatív megvalósítása, amely kompatibilis a felsőbb szintű Bitwarden kliensekkel *, tökéletes önellátó telepítésre, ahol az erőforrásigényes hivatalos szolgáltatás futtatása nem lehet ideális.
    it_it: Implementazione alternativa dell'API del server Bitwarden scritta in Rust e compatibile con i client Bitwarden superiori *, perfetta per il rilascio auto ospitato in cui l'esecuzione del servizio ufficiale pesante in termini di risorse potrebbe non essere ideale.
    ru_ru: Альтернативная реализация API-интерфейса сервера Bitwarden, написанная на Rust и совместимая с клиентами Bitwarden верхнего уровня *, идеально подходит для самостоятельного развертывания, где запуск официального ресурсоемкого сервиса может не быть идеальным.
    pl_pl: Alternatywna implementacja interfejsu API serwera Bitwarden napisana w Rust i kompatybilna z klientami Bitwarden wyższego poziomu *, idealna do samodzielnego wdrażania, w którym uruchamianie oficjalnego ciężkiego serwisu może nie być idealne.
    pt_br: Implementação alternativa da API do servidor Bitwarden escrita em Rust e compatível com os clientes Bitwarden superiores *, perfeita para implantação auto-hospedada em que a execução do serviço oficial pesado em recursos pode não ser ideal.
    sv_se: Alternativ implementering av Bitwarden-serverns API skriven i Rust och kompatibel med översta Bitwarden-klienterna *, perfekt för självhärdad drift där körning av den officiella resurskrävande tjänsten kanske inte är idealisk.
    uk_ua: Альтернативна реалізація API-інтерфейсу сервера Bitwarden, написана на Rust і сумісна з клієнтами Bitwarden вищого рівня *, ідеально підходить для самостійного розгортання, де запуск офіційного ресурсоємкого сервісу може не бути ідеальним.
  developer: Daniel García
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Vaultwarden/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Vaultwarden/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Vaultwarden/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Vaultwarden/screenshot-3.png
  tagline:
    en_us: A self-hosted Bitwarden server
    zh_cn: 自托管的 Bitwarden 服务器
    ar_sa: خادم Bitwarden مستضافة بنفسها
    de_de: Ein selbst gehosteter Bitwarden-Server
    es_es: Un servidor Bitwarden autohospedado
    fr_fr: Un serveur Bitwarden auto-hébergé
    hu_hu: Önellátó Bitwarden szerver
    it_it: Un server Bitwarden auto ospitato
    ru_ru: Самостоятельный сервер Bitwarden
    pl_pl: Serwer Bitwarden autohostowany
    pt_br: Um servidor Bitwarden auto-hospedado
    sv_se: En självhärdad Bitwarden-server
    uk_ua: Самостійний сервер Bitwarden
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Vaultwarden/thumbnail.png
  tips: {}
  title:
    en_us: Vaultwarden
  index: /
  port_map: "10380"
