name: v2raya
services:
  v2raya:
    image: mzz2017/v2raya@sha256:06abe4f4f16876a6695dec1f92d4c02a3ac724253a62b94702502c331993d59e
    container_name: v2raya
    deploy:
      resources:
        reservations:
          memory: 128M
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
    - type: bind
      source: /lib/modules
      target: /lib/modules
      read_only: true
    - type: bind
      source: /etc/resolv.conf
      target: /etc/resolv.conf
    - type: bind
      source: /DATA/AppData/$AppID
      target: /etc/v2raya
x-casaos:
  app_id: org.icewhale.v2raya
  main: v2raya
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/v2raya/assets/icon.svg
  scheme: http
  port_map: '2017'
  index: /
  title:
    en_US: V2rayA
  version: 2.2.7-5
