name: pinchflat
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest@sha256:1f6090ad9940bb6907f6c542ae0c18ecd3df08cd6cfece6617a424adbfbe3740
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
    - target: 8945
      published: '8945'
      protocol: tcp
    restart: unless-stopped
    environment:
    - TZ=$TZ
    - PUID=$PUID
    - PGID=$PGID
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /config
    - type: bind
      source: /DATA/Media/Downloads
      target: /downloads
    container_name: pinchflat
x-casaos:
  id: org.icewhale.pinchflat
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.pinchflat/assets/icon.svg
  main: pinchflat
  port_map: '8945'
  scheme: http
  title:
    en_US: Pinchflat
  version: 2025.9.26
