name: resilio-sync
services:
  resilio-sync:
    environment:
    - PGID=$PGID
    - PUID=$PUID
    - TZ=$TZ
    image: linuxserver/resilio-sync:3.1.2@sha256:a766abff45adcb9e6da3b575503e29764c4cd97d6eec6f790fe3e49e2fdaf45a
    network_mode: bridge
    ports:
    - target: 55555
      published: '55555'
      protocol: tcp
    - target: 8888
      published: '8888'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /sync
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /config
    - type: bind
      source: /DATA/Downloads
      target: /downloads
    privileged: false
    container_name: resilio-sync
x-casaos:
  app_id: org.icewhale.resiliosync
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.resiliosync/assets/icon.svg
  index: /
  port_map: '8888'
  scheme: http
  title:
    en_US: resilio-sync
  version: 3.1.2
