name: playit-agent
services:
  playit-agent:
    restart: unless-stopped
    image: ghcr.io/mafen/playit-docker:latest
    network_mode: bridge
    container_name: playit-agent
x-casaos:
  architectures:
    - amd64
    - arm64
  main: playit-agent
  author: mafen
  category: Utilities
  tips:
    before_install:
      en_us: |
        This is the agent for use with playit.gg's reverse proxy. After having installed the container/app, you have to go to the settings of the container/app and go to the logs. The logs will tell you to click a link to activate the agent. Copy the link (you will have to do it manually with your cursor) and paste it in your web browser in a new tab. This will open a page asking you to login or register. If you have an account already then you can login. If not, register an account. Once you're logged in, it will ask to allow the agent. Allow the agent and remember the agent name. Then head over to https://playit.gg/account/agents. From there you need to select the correct agent, according to the agent name you just were to remember. From there you can add tunnels. Choose the options for the tunnel as you need, and a port in case of doing it manually with TCP, UDP and TCP+UDP. After that use the provided domain and port to connect to the tunnel and use that to get access to your tunneled service!
    en_us: playit.gg is a global proxy that allows anyone to host a server without port forwarding. We use tunneling. Only the server needs to run the program, not every player!
    zh_cn: playit.gg 是一款全球代理服务器，允许任何人在无需端口转发的情况下托管服务器。我们使用隧道技术。只有服务器需要运行该程序，而不是每个玩家！
    ar_sa: playit.gg هو وكيل عالمي يسمح لأي شخص باستضافة خادم دون إعادة توجيه المنفذ. نحن نستخدم النفق. يحتاج الخادم فقط إلى تشغيل البرنامج، وليس كل لاعب!
    de_de: playit.gg ist ein globaler Proxy, der es jedem ermöglicht, einen Server ohne Portweiterleitung zu hosten. Wir verwenden Tunneling. Nur der Server muss das Programm ausführen, nicht jeder Spieler!
    es_es: playit.gg es un proxy global que permite a cualquiera alojar un servidor sin reenvío de puertos. Utilizamos tunneling. Sólo el servidor necesita ejecutar el programa, ¡no todos los jugadores!
    fr_fr: playit.gg est un proxy global qui permet à n'importe qui d'héberger un serveur sans transfert de port. Nous utilisons le tunneling. Seul le serveur a besoin d'exécuter le programme, pas tous les joueurs !
    hu_hu: A playit.gg egy globális proxy, amely lehetővé teszi, hogy bárki porttovábbítás nélkül szervert üzemeltessen. Mi tunnelinget használunk. Csak a szervernek kell futtatnia a programot, nem minden játékosnak!
    it_it: playit.gg è un proxy globale che consente a chiunque di ospitare un server senza port forwarding. Utilizziamo il tunneling. Solo il server deve eseguire il programma, non tutti i giocatori!
    ru_ru: playit.gg - это глобальный прокси-сервер, который позволяет любому желающему разместить у себя сервер без проброса портов. Мы используем туннелирование. Только сервер должен запускать программу, а не каждый игрок!
    pl_pl: playit.gg to globalne proxy, które pozwala każdemu na hostowanie serwera bez przekierowania portów. Używamy tunelowania. Tylko serwer musi uruchomić program, nie każdy gracz!
    pt_br: O playit.gg é um proxy global que permite a qualquer pessoa hospedar um servidor sem encaminhamento de porta. Usamos o tunelamento. Somente o servidor precisa executar o programa, não todos os jogadores!
    sv_se: playit.gg är en global proxy som gör det möjligt för vem som helst att vara värd för en server utan port vidarebefordran. Vi använder tunnlar. Endast servern behöver köra programmet, inte varje spelare!
    uk_ua: playit.gg - це глобальний проксі, який дозволяє будь-кому розмістити сервер без переадресації портів. Ми використовуємо тунелювання. Тільки сервер повинен запускати програму, а не кожен гравець!
  developer: Patrick Lorio
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/playit-agent/icon.png
  tagline:
    en_us: A free reverse proxy for tunneling services (not self-hosted).
    zh_cn: 用于隧道服务的免费反向代理（非自托管）。
    de_de: Ein kostenloser Reverse-Proxy für Tunneling-Dienste (nicht selbst gehostet).
    nl_nl: Een gratis reverse proxy voor tunnelingdiensten (niet zelf gehost).
    es_es: Un proxy inverso gratuito para servicios de túnel (no autoalojado).
    fr_fr: Un proxy inverse gratuit pour les services de tunneling (non auto-hébergé).
    hu_hu: Ingyenes fordított proxy az alagutas szolgáltatásokhoz (nem saját üzemeltetésű).
    it_it: Un reverse proxy gratuito per servizi di tunneling (non self-hosted).
    ru_ru: Бесплатный обратный прокси-сервер для туннельных сервисов (не самостоятельный хостинг).
    pl_pl: Darmowy odwrotny serwer proxy dla usług tunelowania (nie hostowany samodzielnie).
    pt_br: Um proxy reverso gratuito para serviços de tunelamento (não auto-hospedado).
    sv_se: En gratis omvänd proxy för tunneltjänster (inte självhostad).
    uk_ua: Безкоштовний зворотний проксі для тунельних сервісів (не розміщується на власному хостингу).
  store_app_id: playit-agent
  title:
    en_us: Playit Agent
