services:
  openclaw:
    image: icewhaletech/openclaw:2026.5.7
    environment:
      HOME: /home/node
      TERM: xterm-256color
      OPENCLAW_GATEWAY_TOKEN: casaos
    network_mode: bridge
    deploy:
      resources:
        reservations:
          memory: 1G
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID
      target: /home/node/.openclaw
    ports:
    - target: 18789
      published: '24190'
      protocol: tcp
    - target: 18790
      published: '18790'
      protocol: tcp
    init: true
    restart: unless-stopped
    privileged: true
    command:
    - /bin/bash
    - -c
    - /app/start.sh && node dist/index.js gateway --bind lan --allow-unconfigured
      --port '18789'
    container_name: openclaw
name: openclaw
x-casaos:
  app_id: org.icewhale.openclaw
  title:
    de_DE: OpenClaw
    el_GR: OpenClaw
    en_GB: OpenClaw
    en_US: OpenClaw
    fr_FR: OpenClaw
    hr_HR: OpenClaw
    it_IT: OpenClaw
    ja_JP: OpenClaw
    ko_KR: OpenClaw
    nb_NO: OpenClaw
    pt_PT: OpenClaw
    ru_RU: OpenClaw
    sv_SE: OpenClaw
    tr_TR: OpenClaw
    zh_CN: OpenClaw
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/openclaw/assets/icon.svg
  main: openclaw
  port_map: '24190'
  index: ?token=casaos
  scheme: https
  version: 2026.5.7
