name: embystat
services:
  embystat:
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/London
    image: linuxserver/embystat@sha256:adc479353fc0b810c21935a8fe3c2d20d9f7027edc9574477d702ec2ad414754
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 6555
      published: '6555'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/embystat/config
      target: /config
    container_name: embystat
x-casaos:
  app_id: org.icewhale.embystat
  main: embystat
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/embystat/assets/icon.svg
  title:
    en_US: Embystat
  port_map: '6555'
  version: 0.2.0
