name: index-tts
services:
  index-tts:
    image: icewhaletech/index-tts:2.0@sha256:1730d1121cbd7c3e66b209fca037ffeb217c38f4a4ddcb51c04edf799d886b37
    container_name: index-tts
    restart: unless-stopped
    ports:
    - target: 7860
      published: '17869'
      protocol: tcp
    deploy:
      resources:
        reservations:
          memory: 12G
x-casaos:
  id: org.icewhale.indextts
  title:
    de_DE: Index-TTS
    el_GR: Index-TTS
    en_GB: Index-TTS
    en_US: Index-TTS
    fr_FR: Index-TTS
    hr_HR: Index-TTS
    it_IT: Index-TTS
    ja_JP: Index-TTS
    ko_KR: Index-TTS
    nb_NO: Index-TTS
    pt_PT: Index-TTS
    ru_RU: Index-TTS
    sv_SE: Index-TTS
    tr_TR: Index-TTS
    zh_CN: Index-TTS
  main: index-tts
  port_map: '17869'
  index: /
  scheme: http
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.indextts/assets/icon.svg
  version: 2.0.0
