name: albyhub
services:
  albyhub:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
      UMASK: '002'
      WORK_DIR: /data/albyhub
      LOG_EVENTS: true
    command: []
    container_name: albyhub
    image: ghcr.io/getalby/hub:v1.22.2@sha256:dadcb273a6df323996ab19a16d48cc1b44dad13025b579a79ece9d2d65186f0d
    deploy:
      resources:
        reservations:
          memory: 1024M
    ports:
    - target: 8080
      published: '58000'
      protocol: tcp
    restart: on-failure
    stop_grace_period: 1m
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /data
    network_mode: bridge
    privileged: false
x-casaos:
  app_id: org.icewhale.albyhub
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.albyhub/assets/icon.svg
  index: /
  port_map: '58000'
  scheme: http
  title:
    en_US: Alby Hub ✨
  version: 1.22.2
