name: ollama
services:
  ollama:
    image: ollama/ollama:0.24.0@sha256:7db82c93ff9fae4011a2aa10931b1d2c2a228d508b8736366e3fbaee616b2e8c
    container_name: ollama
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped
    ports:
    - target: 11434
      published: '11434'
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/
      target: /root/.ollama
x-casaos:
  app_id: org.icewhale.ollama
  main: ollama
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.ollama/assets/icon.svg
  scheme: http
  port_map: '11434'
  index: /
  title:
    en_US: Ollama
  version: 0.24.0
