name: monica
services:
  monica:
    image: monica:4.1.2@sha256:3027bcfdb37de3482737cdc0fde97b87b4240ee1fbdaf8fab868cf2462792448
    container_name: monica
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
    restart: unless-stopped
    ports:
    - target: 80
      published: '18930'
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/storage
      target: /var/www/html/storage
    environment:
      APP_KEY: ChangeMeBy32KeyLengthOrGenerated
      DB_HOST: monica-db
      DB_USERNAME: monicauser
      DB_PASSWORD: monicasecret
    networks:
    - monica_network
    depends_on:
    - monica-db
  monica-db:
    image: mariadb:11.8.2@sha256:bb961ca672bcbde3df9e385d4ce84b31bb826792711c777f6ce97e49fcd9d38c
    container_name: monica-db
    deploy:
      resources:
        reservations:
          memory: 256M
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/mysql
      target: /var/lib/mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_DATABASE: monica
      MARIADB_USER: monicauser
      MARIADB_PASSWORD: monicasecret
    restart: unless-stopped
    networks:
    - monica_network
networks:
  monica_network:
    driver: bridge
x-casaos:
  app_id: org.icewhale.monica
  main: monica
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.monica/assets/icon.svg
  scheme: ''
  port_map: '18930'
  index: /
  title:
    en_US: Monica
  version: 4.1.2
