name: mariadb
services:
  mariadb:
    image: linuxserver/mariadb:11.4.8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      MYSQL_ROOT_PASSWORD: casaos
      MYSQL_DATABASE: casaos
      MYSQL_USER: casaos
      MYSQL_PASSWORD: casaos
      REMOTE_SQL: ''
    ports:
    - target: 3306
      published: '3306'
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/mariadb/config
      target: /config
    container_name: mariadb
x-casaos:
  app_id: org.icewhale.mariadb
  main: mariadb
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.mariadb/assets/icon.svg
  title:
    en_US: MariaDB
  version: 11.4.8
