name: romm
services:
  romm:
    image: rommapp/romm:4.8.1@sha256:072c87742e974301cf3a08e5cef563e49a00be97233d80b4f1685d04f199038f
    container_name: romm
    deploy:
      resources:
        reservations:
          memory: 512M
    networks:
    - romm-network
    restart: unless-stopped
    ports:
    - 8285:8080
    environment:
    - DB_HOST=romm-db
    - DB_NAME=romm
    - DB_USER=romm-user
    - DB_PASSWD=casaos
    - ROMM_AUTH_SECRET_KEY=""
    - IGDB_CLIENT_ID=""
    - IGDB_CLIENT_SECRET=""
    - SCREENSCRAPER_USER=""
    - SCREENSCRAPER_PASSWORD=""
    - STEAMGRIDDB_API_KEY=""
    volumes:
    - /DATA/AppData/$AppID/resources:/romm/resources
    - /DATA/AppData/$AppID/redis-data:/redis-data
    - /DATA/AppData/$AppID/library:/romm/library
    - /DATA/AppData/$AppID/assets:/romm/assets
    - /DATA/AppData/$AppID/config:/romm/config
    depends_on:
      romm-db:
        condition: service_healthy
        restart: true
  romm-db:
    image: mariadb:11.8.2@sha256:cc77bc4f4dfe94d1c0c5d0f2bc9133e7c8211944bdd3c06df2c84028eb269196
    container_name: romm-db
    restart: unless-stopped
    networks:
    - romm-network
    environment:
    - MARIADB_ROOT_PASSWORD=casaos
    - MARIADB_DATABASE=romm
    - MARIADB_USER=romm-user
    - MARIADB_PASSWORD=casaos
    volumes:
    - /DATA/AppData/$AppID/mysql:/var/lib/mysql
    healthcheck:
      test:
      - CMD
      - healthcheck.sh
      - --connect
      - --innodb_initialized
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  romm-network:
    driver: bridge
x-casaos:
  id: org.icewhale.romm
  main: romm
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.romm/assets/icon.svg
  scheme: http
  port_map: '8285'
  index: /
  title:
    en_US: RomM
  version: 4.8.1
