name: smokeping
services:
  smokeping:
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/London
    image: linuxserver/smokeping:2.9.0
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 80
      published: '10280'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/smokeping/config
      target: /config
    - type: bind
      source: /DATA/AppData/smokeping/data
      target: /data
    container_name: smokeping
x-casaos:
  app_id: com.icewhaletech.smokeping
  main: smokeping
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/smokeping/assets/icon.svg
  title:
    en_US: Smokeping
  port_map: '10280'
  version: 2.9.0
