name: trilium
services:
  trilium:
    command: []
    container_name: trilium
    deploy:
      resources:
        reservations:
          memory: 256M
    image: triliumnext/trilium@sha256:8e6bc939a6d5dbeed42d1b5b155bc790b1c28ca3ac414382d04d626903c62081
    ports:
    - target: 8080
      published: '8088'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID
      target: /home/node/trilium-data
    network_mode: bridge
    privileged: false
x-casaos:
  app_id: org.icewhale.trilium
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/trilium/assets/icon.svg
  index: /
  port_map: '8088'
  scheme: http
  title:
    en_US: Trilium
    zh_CN: Trilium
  version: 0.103.0
