name: icewhale-stable-diffusion-webui
services:
  icewhale-stable-diffusion-webui:
    image: johnguan/stable-diffusion-webui:latest
    runtime: nvidia
    ipc: host
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CPU_FALLBACK=true
    deploy:
      resources:
        reservations:
          memory: 512M
    network_mode: bridge
    ports:
    - target: 7860
      published: '7860'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/Stable-Diffusion-WebUI/models
      target: /data/models
    - type: bind
      source: /DATA/AppData/Stable-Diffusion-WebUI/outputs
      target: /data/outputs
    - type: bind
      source: /DATA/AppData/Stable-Diffusion-WebUI/config
      target: /data/config
    privileged: false
    container_name: icewhale-stable-diffusion-webui
x-casaos:
  app_id: org.icewhale.icewhalestablediffusionwebui
  main: icewhale-stable-diffusion-webui
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.icewhalestablediffusionwebui/assets/icon.svg
  scheme: http
  title:
    en_US: Stable Diffusion
  index: /
  port_map: '7860'
  version: 9.0.0
