name: flaresolverr
services:
  flaresolverr:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
      UMASK: "002"
      LOG_LEVEL: "info"
      LOG_HTML: "false"
      CAPTCHA_SOLVER: "none"
    cpu_shares: 50
    command: []
    container_name: flaresolverr
    deploy:
      resources:
        reservations:
          memory: 64M
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.6
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/FlareSolverr/icon.svg
    ports:
      - target: 8191
        published: "8191"
        protocol: tcp
    restart: unless-stopped
    network_mode: bridge
    privileged: false
x-casaos:
  architectures:                  # a list of architectures that the app supports
      - amd64
      - arm
      - arm64
  author: calganaygun
  category: Networking
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/FlareSolverr/icon.svg
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/FlareSolverr/screenshot-1.png
  index: /
  port_map: "8191"
  scheme: http
  store_app_id: flaresolverr
  title:
    en_US: FlareSolverr
  version: "3.4.6"
  update_at: "2025-11-29"
  release_notes:
    en_US: |-
      - v3.4.6 adds an option to disable image, CSS, and font loading through CDP.
      - The README was updated.
    en_GB: |-
      - v3.4.6 adds an option to disable image, CSS, and font loading through CDP.
      - The README was updated.
    it_IT: |-
      - v3.4.6 adds an option to disable image, CSS, and font loading through CDP.
      - The README was updated.
    nb_NO: |-
      - v3.4.6 adds an option to disable image, CSS, and font loading through CDP.
      - The README was updated.
    zh_CN: |-
      - v3.4.6 adds an option to disable image, CSS, and font loading through CDP.
      - The README was updated.
    ja_JP: |-
      - v3.4.6 adds an option to disable image, CSS, and font loading through CDP.
      - The README was updated.
    ko_KR: |-
      - v3.4.6 adds an option to disable image, CSS, and font loading through CDP.
      - The README was updated.
    fr_FR: |-
      - v3.4.6 adds an option to disable image, CSS, and font loading through CDP.
      - The README was updated.
    de_DE: |-
      - v3.4.6 adds an option to disable image, CSS, and font loading through CDP.
      - The README was updated.
    sv_SE: |-
      - v3.4.6 adds an option to disable image, CSS, and font loading through CDP.
      - The README was updated.
    el_GR: |-
      - v3.4.6 adds an option to disable image, CSS, and font loading through CDP.
      - The README was updated.
    hr_HR: |-
      - v3.4.6 adds an option to disable image, CSS, and font loading through CDP.
      - The README was updated.
    pt_PT: |-
      - v3.4.6 adds an option to disable image, CSS, and font loading through CDP.
      - The README was updated.
    ru_RU: |-
      - v3.4.6 adds an option to disable image, CSS, and font loading through CDP.
      - The README was updated.
    tr_TR: |-
      - v3.4.6 adds an option to disable image, CSS, and font loading through CDP.
      - The README was updated.
  website: ""
  repo: "https://github.com/FlareSolverr/FlareSolverr"
  support: "https://github.com/FlareSolverr/FlareSolverr/issues"
  docs: "https://github.com/FlareSolverr/FlareSolverr#readme"
