name: docmost
services:
  docmost:
    image: docmost/docmost:0.90.0
    container_name: docmost
    deploy:
      resources:
        reservations:
          memory: 512M
    restart: unless-stopped
    ports:
    - target: 3000
      published: '3000'
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/storage
      target: /app/data/storage
    environment:
      APP_URL: http://localhost:3000
      APP_SECRET: gxahngf9wc9ak9ahgpjp03zp1akcr7ry
      DATABASE_URL: postgresql://docmost:jcui51lw747yuuk4zrpm@docmost-db:5432/docmost?schema=public
      REDIS_URL: redis://docmost-redis:6379
    networks:
    - docmost-network
    depends_on:
    - docmost-db
    - docmost-redis
  docmost-db:
    container_name: docmost-db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: jcui51lw747yuuk4zrpm
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/pgdata
      target: /var/lib/postgresql/data
    networks:
    - docmost-network
  docmost-redis:
    container_name: docmost-redis
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/redis
      target: /data
    networks:
    - docmost-network
networks:
  docmost-network:
    driver: bridge
x-casaos:
  main: docmost
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/docmost/assets/icon.svg
  scheme: http
  port_map: '3000'
  index: /
  title:
    en_US: Docmost
  version: 0.90.0
