name: calibre-web
services:
  calibre-web:
    environment:
      DOCKER_MODS: linuxserver/calibre-web:calibre
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: linuxserver/calibre-web:0.6.19
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 8083
        published: "8083"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/Media/Books
        target: /books
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: ""
        - container: DOCKER_MODS
          description:
            en_us: ""
      index: /
      port_map: "8083"
      ports:
        - container: "8083"
          description:
            en_us: ""

      volumes:
        - container: /config
          description:
            en_us: ""
        - container: /books
          description:
            en_us: ""
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: calibre-web
  author: CasaOS Team
  category: Media
  description:
    en_us: Calibre-web is a web app providing a clean interface for browsing, reading and downloading eBooks using an existing Calibre database. It is also possible to integrate google drive and edit metadata and your calibre library through the app itself.
    zh_cn: Calibre-web是一个Web应用程序，提供了一个干净的界面，用于浏览，阅读和下载使用现有Calibre数据库的电子书。也可以通过应用程序本身集成谷歌驱动器并编辑元数据和您的calibre库。
  developer: linuxserver
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Calibre-web/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Calibre-web/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Calibre-web/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Calibre-web/screenshot-3.png
  tagline:
    en_us: Web app for browsing, reading and downloading eBooks stored in a Calibre database
    zh_cn: 用于浏览，阅读和下载存储在Calibre数据库中的电子书的Web应用程序
  thumbnail: ' https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Calibre-web/thumbnail.png'
  tips:
    before_install:
      en_us: |
        | Username | Password |
        | -------- | -------- |
        | `admin`    | `admin123` |
      zh_cn: |
        | 用户名 | 密码 |
        | -------- | -------- |
        | `admin`    | `admin123` |
  title:
    en_us: Calibre-web
