name: tautulli
services:
  tautulli:
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/London
    image: linuxserver/tautulli:2.17.1
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 8181
      published: '8181'
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /config
    container_name: tautulli
x-casaos:
  app_id: org.icewhale.tautulli
  main: tautulli
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.tautulli/assets/icon.svg
  title:
    en_US: Tautulli
  index: /
  port_map: '8181'
  version: 2.17.1
