name: openspeedtest
services:
  openspeedtest:
    image: openspeedtest/latest:v0.0.1
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 3000
        published: "3004"
        protocol: tcp
    restart: always
    x-casaos:
      ports:
        - container: "3000"
          description:
            en_us: ""

    container_name: openspeedtest
x-casaos:
  architectures:
    - amd64
    - arm64
    - ppc64le
    - s390x
    - "386"
    - arm
  main: openspeedtest
  author: OpenSpeedTest
  category: Utilities
  description:
    en_us: An application for launching HTML5 Network Speed Test Server. You can test download & upload speed from any device within your network with a web browser that is IE10 or new.
    zh_cn: 一个用于启动HTML5网络速度测试服务器的应用程序。您可以使用IE10或更高版本的Web浏览器从您的网络中的任何设备上测试下载和上传速度。
    ar_sa: تطبيق لتشغيل خادم اختبار سرعة الشبكة HTML5. يمكنك اختبار سرعة التحميل والتحميل من أي جهاز داخل شبكتك باستخدام متصفح ويب يعمل على IE10 أو أحدث.
    de_de: Eine Anwendung zum Starten eines HTML5-Netzwerkgeschwindigkeitstestservers. Sie können die Download- und Uploadgeschwindigkeit von jedem Gerät in Ihrem Netzwerk mit einem Webbrowser testen, der IE10 oder neuer ist.
    es_es: Una aplicación para iniciar un servidor de prueba de velocidad de red HTML5. Puede probar la velocidad de descarga y carga desde cualquier dispositivo dentro de su red con un navegador web que sea IE10 o superior.
    fr_fr: Une application pour lancer un serveur de test de vitesse de réseau HTML5. Vous pouvez tester la vitesse de téléchargement et de téléchargement à partir de tout appareil dans votre réseau avec un navigateur Web qui est IE10 ou plus récent.
    hu_hu: HTML5 hálózati sebességteszt szerver indítására szolgáló alkalmazás. Bármelyik eszközről tesztelheti a letöltési és feltöltési sebességet a hálózatában egy olyan webböngészővel, amely IE10 vagy újabb.
    it_it: Un'applicazione per avviare un server di test di velocità di rete HTML5. È possibile testare la velocità di download e upload da qualsiasi dispositivo all'interno della rete con un browser web che è IE10 o superiore.
    ru_ru: Приложение для запуска HTML5-сервера тестирования скорости сети. Вы можете проверить скорость загрузки и выгрузки с любого устройства в вашей сети с помощью веб-браузера, который поддерживает IE10 или новее.
    pl_pl: Aplikacja do uruchamiania serwera testów prędkości sieci HTML5. Możesz przetestować prędkość pobierania i wysyłania z dowolnego urządzenia w sieci przy użyciu przeglądarki internetowej, która obsługuje IE10 lub nowszą.
    pt_br: Um aplicativo para iniciar um servidor de teste de velocidade de rede HTML5. Você pode testar a velocidade de download e upload de qualquer dispositivo em sua rede com um navegador da web que seja IE10 ou superior.
    sv_se: En applikation för att starta en HTML5-nätverkshastighetstestserver. Du kan testa nedladdnings- och uppladdningshastighet från vilket enhet som helst i ditt nätverk med en webbläsare som är IE10 eller nyare.
    uk_ua: Додаток для запуску HTML5-сервера тестування швидкості мережі. Ви можете перевірити швидкість завантаження та вивантаження з будь-якого пристрою у мережі за допомогою веб-браузера, який підтримує IE10 або новіші.
  developer: OpenSpeedTest
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/OpenSpeedTest/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/OpenSpeedTest/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/OpenSpeedTest/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/OpenSpeedTest/screenshot-3.png
  tagline:
    en_us: HTML5 Network Speed Test Server.
    zh_cn: HTML5网络速度测试服务器。
    ar_sa: خادم اختبار سرعة الشبكة HTML5.
    de_de: HTML5-Netzwerkgeschwindigkeitstestserver.
    es_es: Servidor de prueba de velocidad de red HTML5.
    fr_fr: Serveur de test de vitesse de réseau HTML5.
    hu_hu: HTML5 hálózati sebességteszt szerver.
    it_it: Server di test di velocità di rete HTML5.
    ru_ru: HTML5-сервер тестирования скорости сети.
    pl_pl: Serwer testów prędkości sieci HTML5.
    pt_br: Servidor de teste de velocidade de rede HTML5.
    sv_se: HTML5-nätverkshastighetstestserver.
    uk_ua: HTML5-сервер тестування швидкості мережі.
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/OpenSpeedTest/thumbnail.png
  tips: {}
  title:
    en_us: OpenSpeedTest
  index: /
  port_map: "3004"
