name: 2fauth
services:
  2fauth:
    image: 2fauth/2fauth:6.1.3
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 8000
      published: '8000'
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID
      target: /2fauth
    environment:
      APP_KEY: SomeRandomStringOf32CharsExactly
    container_name: 2fauth
x-casaos:
  id: org.icewhale.2fauth
  main: 2fauth
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.2fauth/assets/icon.svg
  title:
    en_US: 2FAuth
  index: /
  port_map: '8000'
  version: 6.1.3
