name: Databag
services:
  databag:
    image: balzack/databag:0.1.5
    restart: unless-stopped
    x-casaos:
      volumes:
        - container: /var/lib/databag
          description:
            en_us: database and asset store
      ports:
        - container: '7000'
          description:
            en_us: rest api port
    ports:
      - target: 7000
        published: 7000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/databag/data
        target: /var/lib/databag
x-casaos:
  architectures:
    - amd64
    - arm64
  main: databag
  description:
    en_us: Databag is a federated chat app for self-hosting that focuses on user privacy and security; the service includes clients for iOS, Android, and browser.
  tagline:
    en_us: Messenger for the Decentralized Web
  developer: balzack
  author: Pierre Balzack
  category: Chat
  title:
    en_us: Databag
