name: 1panel
services:
  1panel:
    container_name: 1panel
    deploy:
      resources:
        reservations:
          memory: 512M
    environment:
      - TZ=Asia/Shanghai
    hostname: 1panel
    image: moelin/1panel:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /DATA/AppData/1panel/opt:/opt # 文件存储映射
      - /DATA/AppData/1panel/root:/root # 可选的文件存储映射
    labels:
      createdBy: "Apps"
    network_mode: host
    privileged: false

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: 1panel
  store_app_id: 1panel
  category: Developer
  author: Cp0204
  developer: 1panel.cn
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/1panel/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/1panel/screenshot-1.png
  thumbnail: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/1panel/thumbnail.png
  description:
    en_us: Modern and Open-Source Linux Server Operation and Management Panel
    zh_cn: 现代化、开源的 Linux 服务器运维管理面板
  tagline:
    en_us: 1Panel running in Docker
    zh_cn: Docker方式运行的1Panel
  title:
    en_us: 1Panel
  tips:
    before_install:
      en_us: |
        * Default port: `10086`
        * Default account: `1panel`
        * Default password: `1panel_password`
        * Default portal: `/entrance`

        #### Note
        Due to systemd limitations inside the container, some features are not yet complete.
        Do not click on the bottom right corner of the 1Panel of a containerized deployment to update, you should pull the new image and redeploy to apply the update.

        [Documentation](https://hub.docker.com/r/moelin/1panel)
      zh_cn: |
        * 默认端口：`10086`
        * 默认账户：`1panel`
        * 默认密码：`1panel_password`
        * 默认入口：`/entrance`

        #### 注意事项
        由于容器内部systemd限制，部分功能目前尚不完整。
        不要点击容器化部署的 1Panel 右下角进行更新，应该拉取新镜像，再重新部署来应用更新。

        [文档](https://hub.docker.com/r/moelin/1panel)
  port_map: "10086"
  scheme: http
  index: /entrance
