name: adguard-home
services:
  adguard-home:
    image: adguard/adguardhome:v0.107.76@sha256:5a46f1f459d5b1a4ed3abbdeff000efe99c3b747125538b7e78c1f4712dc3385
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 53
      published: '531'
      protocol: tcp
    - target: 53
      published: '531'
      protocol: udp
    - target: 3000
      published: '3001'
      protocol: tcp
    - target: 853
      published: '853'
      protocol: tcp
    - target: 784
      published: '784'
      protocol: udp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/opt/adguardhome/work
      target: /opt/adguardhome/work
    - type: bind
      source: /DATA/AppData/$AppID/opt/adguardhome/conf
      target: /opt/adguardhome/conf
    container_name: adguard-home
x-casaos:
  id: org.icewhale.adguardhome
  main: adguard-home
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.adguardhome/assets/icon.svg
  title:
    en_US: AdGuard Home
  index: /
  port_map: '3001'
  version: 0.107.76
