name: jdownloader2
services:
  app:
    image: plusminus/jdownloader2-headless:latest
    restart: unless-stopped
    x-casaos:
      volumes:
        - container: /DATA/AppData/jdownloader/config
          description:
            en_us: Configs
        - container: /DATA/Downloads
          description:
            en_us: Downloads
      envs:
        - container: TZ
          description:
            en_us: TimeZone
        - container: UID
          description:
            en_us: Specifies the UID the daemon should run as. All created files will be owned by this UID. Defaults to 1000.
        - container: GID
          description:
            en_us: Specifies the GID for all created files. This only works in combination with the UID. Defaults to 100 for users.
        - container: EMAIL
          description:
            en_us: The MyJDownloader account e-mail. Is written automatically to config-file, if set.
        - container: PASSWORD
          description:
            en_us: The MyJDownloader account password. Is written automatically to config-file, if set.
    environment:
      - UID=$UID
      - GID=$GID
      - TZ=$TZ
      - EMAIL=$EMAIL
      - PASSWORD=$PASSWORD
    volumes:
      - type: bind
        source: /DATA/AppData/jdownloader/config
        target: /opt/JDownloader/cfg
      - type: bind
        source: /DATA/Downloads
        target: /opt/JDownloader/Downloads
    container_name: jdownloader2
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: JDownloader is a free, open-source download management tool with a huge community that makes downloading as easy and fast as it should be. Users can start, stop or pause downloads, set bandwith limitations, auto-extract archives and much more. It's an easy-to-extend framework that can save hours of your valuable time every day!
  tagline:
    en_us: Free & open-source download management tool
  developer: jdownloader
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/JDownloader2/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/JDownloader2/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/JDownloader2/screenshot-2.jpg
  author: Fabio Tea
  category: Utility
  title:
    en_us: JDownloader2
