name: jdownloader2
services:
  jdownloader2:
    image: jlesage/jdownloader-2@sha256:3d6cb102bd9bacff12ab1ca5136a38cb8f93d6595a7ccf5bce60aac4df138ebd
    restart: unless-stopped
    environment:
    - USER_ID=$PUID
    - GROUP_ID=$PGID
    - TZ=$TZ
    - MYJDOWNLOADER_EMAIL=$MYJDOWNLOADER_EMAIL
    - MYJDOWNLOADER_PASSWORD=$MYJDOWNLOADER_PASSWORD
    - MYJDOWNLOADER_DEVICE_NAME=$MYJDOWNLOADER_DEVICE_NAME
    - JDOWNLOADER_HEADLESS=$JDOWNLOADER_HEADLESS
    ports:
    - target: 5800
      published: '5800'
      protocol: tcp
    - target: 5900
      published: '5900'
      protocol: tcp
    - target: 3129
      published: '3129'
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/jdownloader2/config
      target: /config
    - type: bind
      source: /DATA/Downloads
      target: /output
    container_name: jdownloader2
x-casaos:
  app_id: org.icewhale.jdownloader2
  main: jdownloader2
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/jdownloader2/assets/icon.svg
  port_map: '5800'
  scheme: http
  title:
    en_US: JDownloader2
  version: 26.3.1
