name: nextcloud
services:
  nextcloud:
    image: nextcloud@sha256:92da6b0a45c52903fc4a4eed2e7274fd89ff3ef05f501299d9df810c804cc59b
    deploy:
      resources:
        reservations:
          memory: 512M
    network_mode: bridge
    ports:
    - target: 80
      published: '10081'
      protocol: tcp
    - target: 443
      published: '10443'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/var/www/html
      target: /var/www/html
    container_name: nextcloud
x-casaos:
  app_id: org.icewhale.nextcloud
  main: nextcloud
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/nextcloud/assets/icon.svg
  title:
    en_US: Nextcloud
  index: /
  port_map: '10081'
  version: 33.0.3
