name: webdav
services:
  webdav:
    cpu_shares: 90
    command: []
    container_name: webdav
    deploy:
      resources:
        limits:
          memory: 15806M
    environment:
      - GID=1000
      - PASSWORD=casaos
      - TZ=Europe/Madrid
      - UDI=1000
      - USERNAME=casaos
    image: ugeek/webdav:amd64
    labels:
      icon: https://icon.casaos.io/main/all/webdav.png
    ports:
      - target: 80
        published: "5005"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/ZimaOS-HD/Media
        target: /media
    network_mode: bridge
    privileged: false
x-casaos:
  architectures:
    - amd64
    - "386"
    - arm64
    - arm
  main: webdav
  author: CasaOS Team
  category: Utilities
  description:
    en_us: WebDAV is a web-based protocol that allows you to share and manage files over the internet, providing a collaborative environment for file editing and versioning.
    zh_cn: WebDAV 是一个基于 Web 的协议，允许您通过互联网共享和管理文件，提供一个协作环境来进行文件编辑和版本控制。
    ar_sa: WebDAV هو بروتوكول قائم على الويب يسمح لك بمشاركة وإدارة الملفات عبر الإنترنت، مما يوفر بيئة تعاونية لتحرير الملفات والتحكم في الإصدارات.
    de_de: WebDAV ist ein webbasiertes Protokoll, das es Ihnen ermöglicht, Dateien über das Internet zu teilen und zu verwalten und eine kollaborative Umgebung für die Dateibearbeitung und Versionskontrolle bietet.
    es_es: WebDAV es un protocolo basado en web que le permite compartir y administrar archivos a través de Internet, proporcionando un entorno colaborativo para la edición y el control de versiones de archivos.
    fr_fr: WebDAV est un protocole basé sur le web qui vous permet de partager et de gérer des fichiers sur Internet, offrant un environnement collaboratif pour l'édition et le contrôle de version des fichiers.
    hu_hu: A WebDAV egy webalapú protokoll, amely lehetővé teszi a fájlok megosztását és kezelését az interneten keresztül, együttműködési környezetet biztosítva a fájlszerkesztéshez és a verziókövetéshez.
    it_it: WebDAV è un protocollo basato sul web che consente di condividere e gestire file su Internet, fornendo un ambiente collaborativo per la modifica e il controllo delle versioni dei file.
    ru_ru: WebDAV - это веб-протокол, который позволяет вам обмениваться файлами и управлять ими через Интернет, обеспечивая совместную среду для редактирования файлов и контроля версий.
    pl_pl: WebDAV to protokół oparty na sieci web, który umożliwia udostępnianie i zarządzanie plikami przez Internet, zapewniając środowisko współpracy do edycji plików i kontroli wersji.
    pt_br: WebDAV é um protocolo baseado na web que permite compartilhar e gerenciar arquivos pela Internet, fornecendo um ambiente colaborativo para edição e controle de versão de arquivos.
    sv_se: WebDAV är ett webbaserat protokoll som låter dig dela och hantera filer över internet, vilket ger en samarbetsmiljö för filredigering och versionskontroll.
    uk_ua: WebDAV - це веб-протокол, який дозволяє вам обмінюватися файлами та керувати ними через Інтернет, забезпечуючи спільне середовище для редагування файлів та контролю версій.
  developer: CasaOS Team
  icon: https://icon.casaos.io/main/all/webdav.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/WebDAV/screenshot-1.png
  tagline:
    en_us: A web-based file sharing and management protocol
    zh_cn: 基于 Web 的文件共享和管理协议
    ar_sa: بروتوكول مشاركة وإدارة الملفات قائم على الويب
    de_de: Ein webbasiertes Dateifreigabe- und Verwaltungsprotokoll
    es_es: Un protocolo de intercambio y gestión de archivos basado en web
    fr_fr: Un protocole de partage et de gestion de fichiers basé sur le web
    hu_hu: Webalapú fájlmegosztási és -kezelési protokoll
    it_it: Un protocollo di condivisione e gestione dei file basato sul web
    ru_ru: Веб-протокол обмена и управления файлами
    pl_pl: Protokół udostępniania i zarządzania plikami oparty na sieci web
    pt_br: Um protocolo de compartilhamento e gerenciamento de arquivos baseado na web
    sv_se: Ett webbaserat protokoll för fildelning och hantering
    uk_ua: Веб-протокол обміну та управління файлами
  tips:
    before_install:
      en_us: |
        Default Account
        
        | Username | Password |
        |----------|----------|
        | `casaos`    | `casaos` |

      zh_cn: |
        默认账号
        
        | Username | Password   |
        | -------- | ---------- |
        | `casaos`    | `casaos` |
  title:
    en_us: WebDAV
  index: /
  port_map: "5005"