name: tailscale
services:
  tailscale:
    image: tailscale/tailscale:v1.98.3@sha256:36b7271dc1bfe146a6d4363553d830ae5499f929a52eea990d0df4e749843b00
    container_name: tailscale
    deploy:
      resources:
        reservations:
          memory: 128M
    network_mode: host
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID
      target: /var/lib/tailscale
    - type: bind
      source: /dev/net/tun
      target: /dev/net/tun
    environment:
      TS_STATE_DIR: /var/lib/tailscale
    cap_add:
    - NET_ADMIN
    - NET_RAW
    entrypoint: /bin/sh -c "tailscaled --state=/var/lib/tailscale/tailscaled.state
      & sleep 10; tailscale web --listen 0.0.0.0:5252"
x-casaos:
  app_id: org.icewhale.tailscale
  main: tailscale
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.tailscale/assets/icon.svg
  scheme: ''
  port_map: '5252'
  index: /
  title:
    en_US: Tailscale
  version: 1.98.3
