name: virt-manager
services: 
  virt-manager:
    restart: always
    devices:
      - /dev/kvm:/dev/kvm
    environment:
      # Set DARK_MODE to true to enable dark mode
      DARK_MODE: false

      # Set HOSTS: "['qemu:///session']" to connect to a user session
      HOSTS: "['qemu:///system']"
    image: mber5/virt-manager:latest
    network_mode: bridge
    ports:
      - target: 80
        published: "8185"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /var/lib/libvirt
        target: /var/lib/libvirt
      - type: bind
        source: /DATA/Downloads
        target: /DATA/Downloads
    
