name: karakeep
services:
  karakeep:
    image: ghcr.io/karakeep-app/karakeep@sha256:64d6a9bbf2d37b5c808cf06b5d87f1f1c7846fdd3844724145a9741aeb06fd31
    container_name: karakeep
    deploy:
      resources:
        reservations:
          memory: 512M
    restart: unless-stopped
    ports:
    - target: 3000
      published: '14592'
      protocol: tcp
    networks:
    - karakeep
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /data
    environment:
      MEILI_ADDR: http://karakeep-meilisearch:7700
      BROWSER_WEB_URL: http://karakeep-chrome:9222
      DATA_DIR: /data
      NEXTAUTH_URL: http://localhost:14592
      NEXTAUTH_SECRET: change_this_to_a_long_random_string
      MEILI_MASTER_KEY: change_this_to_a_long_random_string
      OPENAI_API_KEY: ''
  karakeep-chrome:
    image: gcr.io/zenika-hub/alpine-chrome@sha256:1a0046448e0bb6c275c88f86e01faf0de62b02ec8572901256ada0a8c08be23f
    container_name: karakeep-chrome
    deploy:
      resources:
        reservations:
          memory: 512M
    restart: unless-stopped
    networks:
    - karakeep
    command:
    - --no-sandbox
    - --disable-gpu
    - --disable-dev-shm-usage
    - --remote-debugging-address=0.0.0.0
    - --remote-debugging-port=9222
    - --hide-scrollbars
  karakeep-meilisearch:
    image: getmeili/meilisearch@sha256:860fa4baed04ae1c235de870edab0c8006227546dea1bbb6411fbfc5e27cf1db
    container_name: karakeep-meilisearch
    deploy:
      resources:
        reservations:
          memory: 256M
    restart: unless-stopped
    networks:
    - karakeep
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/meilisearch
      target: /meili_data
    environment:
      MEILI_MASTER_KEY: change_this_to_a_long_random_string
      MEILI_NO_ANALYTICS: 'true'
networks:
  karakeep:
    driver: bridge
x-casaos:
  app_id: org.icewhale.karakeep
  main: karakeep
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/karakeep/assets/icon.svg
  scheme: http
  port_map: '14592'
  index: /
  title:
    en_US: Karakeep
  version: 0.32.0
