name: motioneye
services:
  motioneye:
    container_name: motioneye
    image: ccrisan/motioneye:master-amd64
    ports:
    - target: 8765
      published: '8765'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/motioneye/config
      target: /etc/motioneye
    - type: bind
      source: /DATA/Media/motioneye
      target: /var/lib/motioneye
    network_mode: bridge
    privileged: false
x-casaos:
  id: org.icewhale.motioneye
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.motioneye/assets/icon.svg
  index: /
  main: motioneye
  port_map: '8765'
  scheme: http
  title:
    en_US: Motioneye
  version: 0.44.0
