name: myspeed
services:
  myspeed:
    container_name: myspeed
    deploy:
      resources:
        limits:
          memory: 256M
    image: germannewsmaker/myspeed:1.0.8
    ports:
      - target: 5216
        published: "5216"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /myspeed/data
    network_mode: bridge
    privileged: false
    x-casaos:
      ports:
        - container: "5216"
          description:
            en_us: WebUI HTTP Port
          protocol: tcp
      volumes:
        - container: /myspeed/data
          description:
            en_us: MySpeed data folder

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: myspeed
  author: joaobosconff
  category: Utilities
  description:
    en_us: MySpeed is a speed test analysis software that stores the speed of your internet for up to 30 days. This can also be useful if you want to know when your network might have drops or if you want to check if your internet matches the booked values from your contract.
    pt_br: MySpeed ​​é um software de análise de teste de velocidade que armazena a velocidade da sua internet por até 30 dias. Isso também pode ser útil se você quiser saber quando sua rede pode sofrer quedas ou se quiser verificar se sua internet corresponde aos valores contratados em seu contrato.
  developer: Mathias Wagner
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/MySpeed/icon.png
  screenshot_link:
  - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/MySpeed/screenshot-1.png
  - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/MySpeed/screenshot-2.png
  - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/MySpeed/screenshot-3.png
  tagline:
    en_us: Analysis software that shows your internet speed for up to 30 days.
    pt_br: Software de análise que mostra a velocidade da sua internet por até 30 dias.
  title:
    en_us: MySpeed
    pt_br: MySpeed
  index: /
  port_map: "5216"
