name: turbodiffusion_nvidia
services:
  turbodiffusion:
    image: icewhaletech/turbodiffusion:20260312
    container_name: turbodiffusion
    deploy:
      resources:
        reservations:
          memory: 40G
          devices:
          - driver: nvidia
            count: all
            capabilities:
            - gpu
    environment:
      MODEL_PATHS: /workspace/TurboDiffusion/checkpoints_host,/workspace/TurboDiffusion/checkpoints
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,video
      CUDA_HOME: /usr/local/cuda
      PYTHONPATH: /workspace/TurboDiffusion/turbodiffusion
    ports:
    - target: 7860
      published: '27860'
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/models
      target: /workspace/TurboDiffusion/checkpoints_host
    - type: bind
      source: /DATA/AppData/$AppID/outputs
      target: /workspace/TurboDiffusion/outputs
    working_dir: /workspace/TurboDiffusion
    command:
    - python
    - turbodiffusion/app_gradio.py
    restart: unless-stopped
x-casaos:
  id: org.icewhale.turbodiffusionnvidia
  title:
    de_DE: TurboDiffusion(Nvidia GPU)
    el_GR: TurboDiffusion(Nvidia GPU)
    en_GB: TurboDiffusion(Nvidia GPU)
    en_US: TurboDiffusion(Nvidia GPU)
    fr_FR: TurboDiffusion(Nvidia GPU)
    hr_HR: TurboDiffusion(Nvidia GPU)
    it_IT: TurboDiffusion(Nvidia GPU)
    ja_JP: TurboDiffusion(Nvidia GPU)
    ko_KR: TurboDiffusion(Nvidia GPU)
    nb_NO: TurboDiffusion(Nvidia GPU)
    pt_PT: TurboDiffusion(Nvidia GPU)
    ru_RU: TurboDiffusion(Nvidia GPU)
    sv_SE: TurboDiffusion(Nvidia GPU)
    tr_TR: TurboDiffusion(Nvidia GPU)
    zh_CN: TurboDiffusion(Nvidia GPU)
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.turbodiffusionnvidia/assets/icon.png
  main: turbodiffusion
  port_map: '27860'
  index: /
  scheme: http
  version: 20260312.0.0
