name: homebridge
version: '2'
services:
  homebridge:
    image: homebridge/homebridge@sha256:4a3964f08b837ac2beab1ce99d7d22d4320d1280c5381242628c88c2a61f0e45
    restart: always
    network_mode: host
    volumes:
    - /DATA/AppData/$AppID/config:/homebridge
    logging:
      driver: json-file
      options:
        max-size: 10mb
        max-file: '1'
x-casaos:
  app_id: com.icewhaletech.homebridge
  main: homebridge
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/homebridge/assets/icon.svg
  title:
    en_US: Homebridge
  index: /
  port_map: '8581'
  version: 2.1.0
