name: homebridge
version: '2'
services:
  homebridge:
    # had to use homebridge/homebridge:latest because there are no versions listed
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - /DATA/AppData/$AppID/config:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
x-casaos:
    architectures:                  # a list of architectures that the app supports
        - amd64
        - arm
        - arm64
    main: homebridge                 # the name of the main service under `services`
    author: UnderCurve
    category: Home Automation
    description:                    # multiple locales are supported
        en_us: Homebridge is a lightweight NodeJS server you can run on your home network that emulates the iOS HomeKit API. It supports Plugins, which are community-contributed modules that provide a basic bridge from HomeKit to various 3rd-party APIs provided by manufacturers of "smart home" devices.
    developer: Homebridge
    icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Homebridge/icon.png
    screenshot_link:
      - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Homebridge/screenshot-1.png
      - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Homebridge/screenshot-2.png
    tagline:                        # multiple locales are supported
        en_us: HomeKit support for the impatient.
    title:                          # multiple locales are supported
        en_us: Homebridge
    index: /                        # the index page for web UI, e.g. index.html
    port_map: "8581"
