name: homebridge
version: '2'
services:
  homebridge:
    image: homebridge/homebridge@sha256:e0bb7f5ef21f57afae10493e793d36b94513fccc23a63e766ce5002d26444d37
    restart: always
    network_mode: host
    volumes:
    - /DATA/AppData/$AppID/config:/homebridge
    logging:
      driver: json-file
      options:
        max-size: 10mb
        max-file: '1'
x-casaos:
  main: homebridge
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/homebridge/assets/icon.svg
  title:
    en_US: Homebridge
  index: /
  port_map: '8581'
  version: 2.1.0
