name: freshrss
services:
  freshrss:
    restart: unless-stopped
    environment:
      TZ: ''
      CRON_MIN: 1,31
    image: freshrss/freshrss:1.29.1@sha256:0821649c78527e14ed73018e5122001b1c58f98a4c9b0c8ad1b9277d15769d54
    network_mode: bridge
    ports:
    - target: 80
      published: '8749'
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/freshrss/data
      target: /var/www/FreshRSS/data
    - type: bind
      source: /DATA/AppData/freshrss/extensions
      target: /var/www/FreshRSS/extensions
    container_name: freshrss
x-casaos:
  id: org.icewhale.freshrss
  main: freshrss
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.freshrss/assets/icon.svg
  port_map: '8749'
  scheme: http
  title:
    en_US: FreshRSS
  version: 1.29.1
