name: pocketbase
services:
  pocketbase:
    image: argonptg/pocketbase:0.25.9
    deploy:
      resources:
        limits:
          memory: 1024M
    network_mode: bridge
    ports:
      - target: 8090
        published: "8090"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/pb_data
        target: /pb_data
    container_name: pocketbase
x-casaos:
  architectures:
    - amd64
  main: pocketbase
  author: CasaOS Team
  category: Developer
  description:
    en_us: PocketBase is an open-source backend solution that combines a real-time database, authentication, file storage, and an admin dashboard into a single, portable executable. 
    pt_br: PocketBase é uma solução de backend de código aberto que combina um banco de dados em tempo real, autenticação, armazenamento de arquivos e um painel de administração em um único executável portátil.
  developer: Gani Georgiev
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/PocketBase/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/PocketBase/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/PocketBase/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/PocketBase/screenshot-3.png
  tagline:
    en_us: "Open Source realtime backend in 1 file"
    pt_br: "Backend open source em tempo real em um único arquivo"
  tips:
    before_install:
      en_us: |
        Default Account
        | Email | Password |
        | ----- | -------- |
        | `casaos@admin.local` | `adminpocketbase` |
      pt_br: |
        Conta Padrão
        | Email | Senha |
        | ----- | -------- |
        | `casaos@admin.local` | `adminpocketbase` |
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/PocketBase/thumbnail.png
  title:
    en_us: PocketBase
  index: /_/
  port_map: "8090"