name: immich
services:
  immich-server:
    deploy:
      resources:
        reservations:
          memory: 1024M
    container_name: immich-server
    hostname: immich-server
    image: ghcr.io/immich-app/immich-server:v2.7.2@sha256:87d31d062ccc7675b29be1736a6e6fbf9d6d6c9920e1f3275a87671edecf83ca
    volumes:
    - /DATA/Gallery/immich:/usr/src/app/upload
    - /etc/localtime:/etc/localtime:ro
    environment:
      DB_DATABASE_NAME: immich
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
    ports:
    - 2283:2283
    depends_on:
    - redis
    - database
    restart: unless-stopped
    healthcheck:
      disable: false
    networks:
    - immich
  immich-machine-learning:
    container_name: immich-machine-learning
    hostname: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v2.7.2@sha256:ebf6321014e3a4f4dbd12a2659baffcf2265637f853a885aa107dc577b554ce0
    environment:
      DB_DATABASE_NAME: immich
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
    restart: unless-stopped
    volumes:
    - /DATA/AppData/immich/model-cache:/cache
    healthcheck:
      disable: false
    networks:
    - immich
  redis:
    container_name: immich-redis
    hostname: immich-redis
    image: docker.io/valkey/valkey:9@sha256:3eeb09785cd61ec8e3be35f8804c8892080f3ca21934d628abc24ee4ed1698f6
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    networks:
    - immich
  database:
    container_name: immich-postgres
    hostname: immich-postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
    - /DATA/AppData/immich/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
    - immich
networks:
  immich:
    driver: bridge
x-casaos:
  id: org.icewhale.immich
  main: immich-server
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.immich/assets/icon.svg
  title:
    en_US: Immich
  port_map: '2283'
  scheme: http
  index: /
  version: 2.7.2
