name: homebridge
version: '2'
services:
  homebridge:
    image: homebridge/homebridge:latest@sha256:b20f2088e71fb2d24ce38f999aee70c4da5659bf77c8ef9ec790fb28fb0d37f6
    restart: always
    network_mode: host
    volumes:
    - /DATA/AppData/$AppID/config:/homebridge
    logging:
      driver: json-file
      options:
        max-size: 10mb
        max-file: '1'
x-casaos:
  id: org.icewhale.homebridge
  main: homebridge
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.homebridge/assets/icon.svg
  title:
    en_US: Homebridge
  index: /
  port_map: '8581'
  version: 2.1.0
