name: homebridge
version: '2'
services:
  homebridge:
    # had to use homebridge/homebridge:latest because there are no versions listed
    image: homebridge/homebridge:latest@sha256:fb58d3b832b286b7c8469a12c4cb671e126d186418782a1fc98f9998065de402
    restart: always
    network_mode: host
    volumes:
      - /DATA/AppData/$AppID/config:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
x-casaos:
  id: org.icewhale.homebridge
  main: homebridge
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.homebridge/assets/icon.svg
  title:
    en_US: Homebridge
  index: /
  port_map: "8581"
  version: "2.1.0"
