name: homebridge
version: '2'
services:
  homebridge:
    image: homebridge/homebridge:latest@sha256:1c9531bb2a156f68cd5f49f3c9d1bca286f95fbc9c348c13dc8df77fda17a546
    restart: always
    network_mode: host
    volumes:
      - /DATA/AppData/$AppID/config:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
x-casaos:
  id: org.icewhale.homebridge
  main: homebridge
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.homebridge/assets/icon.svg
  title:
    en_US: Homebridge
  index: /
  port_map: "8581"
  version: "2.1.0"
