name: copyparty
services:
  copyparty:
    image: icewhaletech/copyparty:1.20.13
    container_name: copyparty
    ports:
    - target: 3923
      published: '29708'
      protocol: tcp
    network_mode: bridge
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/w
      target: /w
    - type: bind
      source: /DATA/AppData/$AppID/confg
      target: /cfg
    deploy:
      resources:
        reservations:
          memory: 512m
    stdin_open: true
    tty: true
    restart: unless-stopped
x-casaos:
  app_id: org.icewhale.copyparty
  title:
    de_DE: CopyParty
    el_GR: CopyParty
    en_GB: CopyParty
    en_US: CopyParty
    fr_FR: CopyParty
    hr_HR: CopyParty
    it_IT: CopyParty
    ja_JP: CopyParty
    ko_KR: CopyParty
    nb_NO: CopyParty
    pt_PT: CopyParty
    ru_RU: CopyParty
    sv_SE: CopyParty
    tr_TR: CopyParty
    zh_CN: CopyParty
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/copyparty/assets/icon.svg
  index: /
  main: copyparty
  port_map: '29708'
  scheme: http
  version: 1.20.13
