name: chatgpt-next-web
services:
  chatgpt-next-web:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
      CODE: ''
      PROXY_URL: ''
      BASE_URL: https://api.openai.com
    image: yidadaa/chatgpt-next-web@sha256:eaaa469ddeeb5fa58fb35f8767e9e096a2f1c8468c54b6703323624bf3071c5a
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 3000
      published: '3000'
      protocol: tcp
    restart: unless-stopped
    container_name: chatgpt-next-web
x-casaos:
  app_id: org.icewhale.chatgptnextweb
  main: chatgpt-next-web
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/chatgpt-next-web/assets/icon.svg
  title:
    en_US: ChatGPT Next Web
  port_map: '3000'
  version: 2.16.1
