name: logseq
services:
  logseq:
    environment:
      PGID: "0"
      PUID: "0"
    image: correctroad/logseq:v0.10.9
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 3000
        published: "3325"
        protocol: tcp   
      - target: 12315
        published: "12315"
        protocol: tcp
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/logseq/config
        target: /config
      - type: bind
        source: /DATA/Documents/Notes
        target: /notes
    x-casaos:
      ports:
        - container: "3325"
          description:
            en_us: ""
      volumes:
        - container: /config
          description:
            en_us: ""
        - container: /notes
          description:
            en_us: ""
    container_name: logseq
x-casaos:
  architectures:
    - amd64
    - arm64
  main: logseq
  author: CasaOS Team
  category: Notes
  description:
    en_us: A privacy-first, open-source platform for knowledge management and collaboration.
    zh_cn: A privacy-first, open-source platform for knowledge management and collaboration.
  developer: Logseq  Team
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Logseq/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Logseq/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Logseq/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Logseq/screenshot-3.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Logseq/screenshot-4.png
  tagline:
    en_us: A privacy-first, open-source platform for knowledge management and collaboration.
    zh_cn: A privacy-first, open-source platform for knowledge management and collaboration.
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Logseq/thumbnail.png
  tips: {}
  title:
    en_us: Logseq
  port_map: "3325"
