name: threadfin
services:
  threadfin:
    image: fyb3roptik/threadfin@sha256:96122ab220e14b881cbd40d7f8c7b022e1f9c6ecfe05aca2ab801e0321dc0d61
    restart: unless-stopped
    environment:
    - THREADFIN_BRANCH=main
    - THREADFIN_DEBUG=0
    ports:
    - target: 34400
      published: '34400'
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/threadfin/config
      target: /home/threadfin/conf/data
    - type: bind
      source: /DATA/AppData/threadfin/backup
      target: /home/threadfin/conf/backup
    container_name: threadfin
x-casaos:
  app_id: org.icewhale.threadfin
  main: threadfin
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/threadfin/assets/icon.svg
  index: /web/
  port_map: '34400'
  scheme: http
  title:
    en_US: Threadfin
    zh_CN: Threadfin
  version: 1.2.37
