name: readarr
services:
  readarr:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: linuxserver/readarr@sha256:c39c1fe2e48e9353a2d81294d70b7624975ae8d603c3cae8df77583d3efeca5b
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 8787
      published: '8787'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /config
    - type: bind
      source: /DATA/Media/Books
      target: /books
    - type: bind
      source: /DATA/Downloads
      target: /downloads
    container_name: readarr
x-casaos:
  app_id: org.icewhale.readarr
  main: readarr
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/readarr/assets/icon.svg
  title:
    en_US: Readarr
  port_map: '8787'
  version: 0.3.10-develop
