name: ztnet
services:
  ztnet:
    image: sinamics/ztnet:0.7.18@sha256:ee7ad23fcbb5a4272decd72b9f91d02b65f25687b90131a0bd202d6b8bc665ae
    container_name: ztnet
    deploy:
      resources:
        reservations:
          memory: 256M
    restart: unless-stopped
    working_dir: /app
    ports:
    - target: 3000
      published: '3050'
      protocol: tcp
    volumes:
    - type: bind
      source: /var/lib/zerotier-one
      target: /var/lib/zerotier-one
    environment:
      ZT_ADDR: http://172.17.0.1:9993
      POSTGRES_HOST: ztnet-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ztnet
      POSTGRES_PASSWORD: ztnetbl5hbv98wl89x9v
      POSTGRES_DB: ztnet
      NEXTAUTH_URL: http://0.0.0.0:3050
      NEXTAUTH_SECRET: mn6vor005ncgnu9iuqxn8bg
      NEXTAUTH_URL_INTERNAL: http://ztnet:3000
    networks:
    - ztnet-network
    depends_on:
    - ztnet-postgres
  ztnet-postgres:
    container_name: ztnet-postgres
    image: postgres:15.2-alpine@sha256:12cbba911ab20aff0594c832f0639f71bb2b6a6d5ea72adc91f3eafe7c152afd
    restart: unless-stopped
    environment:
      POSTGRES_USER: ztnet
      POSTGRES_PASSWORD: ztnetbl5hbv98wl89x9v
      POSTGRES_DB: ztnet
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/postgres-data
      target: /var/lib/postgresql/data
    networks:
    - ztnet-network
networks:
  ztnet-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.31.255.0/29
x-casaos:
  id: org.icewhale.ztnet
  main: ztnet
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.ztnet/assets/icon.svg
  scheme: http
  port_map: '3050'
  index: /
  title:
    en_US: ZTnet
  version: 0.7.18
