name: siyuan-note
services:
  siyuan-note:
    command: --accessAuthCode=casaos --workspace=/siyuan/workspace/
    environment:
      PUID: '1000'
      PGID: '1000'
    image: b3log/siyuan:v3.6.5@sha256:09591e042f032e6236a9df1a2dba6b733223095b135518d91f734d454bae5a85
    deploy:
      resources:
        reservations:
          memory: 512M
    network_mode: bridge
    ports:
    - target: 6806
      published: '6806'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/workspace
      target: /siyuan/workspace
    container_name: siyuan-note
x-casaos:
  app_id: org.icewhale.siyuannote
  main: siyuan-note
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.siyuannote/assets/icon.svg
  title:
    en_US: SiYuan Note
    zh_CN: 思源笔记
  index: null
  port_map: '6806'
  version: 3.6.5
