name: dsh-harness
services:
  dsh:
    command:
    container_name: dsh-harness
    entrypoint:
    image: ghcr.io/smanx/deepseek-harness:latest@sha256:029f870a519f45cf023f407e13331b0e08009eae919b02a7061b839c622aedbf
    networks:
      - default
    ports:
      - mode: ingress
        target: 3080
        published: "3080"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID
        target: /root/.dsh
        bind:
          create_host_path: true
x-casaos:
  id: org.icewhale.dsh-harness
  main: dsh
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.dsh-harness/assets/icon.png
  title:
    en_US: DeepSeekHarness
  index: /
  port_map: "3080"
  scheme: http
  version: "0.1.0"
