name: flowise
services:
  flowise:
    image: flowiseai/flowise:3.1.2
    container_name: flowise
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 256M
    environment:
    - PORT=3025
    - DATABASE_PATH=/root/.flowise
    - APIKEY_PATH=/root/.flowise
    - SECRETKEY_PATH=/root/.flowise
    - LOG_PATH=/root/.flowise/logs
    - BLOB_STORAGE_PATH=/root/.flowise/storage
    - FLOWISE_USERNAME=casaos
    - FLOWISE_PASSWORD=casaos
    ports:
    - 3025:3025
    volumes:
    - /DATA/AppData/$AppID:/root/.flowise
    entrypoint: /bin/sh -c "sleep 3; flowise start"
x-casaos:
  main: flowise
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/flowise/assets/icon.svg
  title:
    en_US: Flowise
  port_map: '3025'
  scheme: http
  index: /
  version: 3.1.2
