name: bili-sync
services:
  bili-sync-rs:
    image: amtoaer/bili-sync-rs:v2.5.0
    restart: unless-stopped
    network_mode: bridge
    tty: false
    user: 0:0
    hostname: bili-sync-rs
    container_name: bili-sync-rs
    ports:
      - 12345:12345
    volumes:
      - /DATA/AppData/bili-sync:/app/.config/bili-sync
      - /DATA:/DATA
x-casaos:
  architectures:
    - amd64
  main: bili-sync-rs
  author: CorrectRoadH
  category: Media
  description:
    en_us: bili-sync is a Bilibili synchronization tool written specifically for NAS users, powered by Rust & Tokio.
    zh_cn: bili-sync 是一款专为 NAS 用户编写的哔哩哔哩同步工具，由 Rust & Tokio 驱动。
  developer: amtoaer
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Bili-Sync/logo.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Bili-Sync/screenshot-1.png
  tagline:
    en_us: bili-sync is a Bilibili synchronization tool written specifically for NAS users, powered by Rust & Tokio.
    zh_cn: 由 Rust & Tokio 驱动的哔哩哔哩同步工具
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Bili-Sync/screenshot-1.png
  tips: 
    before_install:
    en_us: |
      see https://bili-sync.allwens.work/quick-start to change your config in /AppData/bili-sync
    zh_cn: |
      看 https://bili-sync.allwens.work/quick-start 去修改你的配置在 /AppData/bili-sync
  title:
    en_us: Bili-sync
  port_map: "12345"