name: openspeedtest
services:
  openspeedtest:
    image: openspeedtest/latest:v2.0.6@sha256:6ef09fe062bf9088c9781bd31b405d6103fee1b4e9293d7f5364ed20e4ed1eb2
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 3000
      published: '3004'
      protocol: tcp
    restart: always
    container_name: openspeedtest
x-casaos:
  app_id: org.icewhale.openspeedtest
  main: openspeedtest
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.openspeedtest/assets/icon.svg
  title:
    en_US: OpenSpeedTest
  index: /
  port_map: '3004'
  version: 2.0.6
