name: commafeed
services:
  commafeed:
    image: athou/commafeed:7.3.2-h2
    environment:
      COMMAFEED_HTTP_CLIENT_BLOCK_LOCAL_ADDRESSES: "true"
    ports:
      - target: 8082
        published: "8082"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /commafeed/data
    x-casaos:
      ports:
        - container: "8082"
          description:
            en_US: Web UI port
      volumes:
        - container: /commafeed/data
          description:
            en_US: CommaFeed data directory
x-casaos:
  id: org.icewhale.commafeed
  architectures:
    - amd64
    - arm64
  main: commafeed
  index: /
  port_map: "8082"
  scheme: http
  icon: https://raw.githubusercontent.com/Athou/commafeed/7.3.2/commafeed-client/public/favicon.svg
  tagline:
    en_US: Google Reader-inspired self-hosted RSS reader
  description:
    en_US: CommaFeed is a self-hosted RSS reader with OPML import/export, mobile-friendly layouts, and native mobile app APIs.
    zh_CN: CommaFeed 是一款自托管 RSS 阅读器，支持 OPML 导入/导出、移动端友好布局和原生移动应用 API。
    de_DE: CommaFeed ist ein selbstgehosteter RSS-Reader mit OPML-Import/-Export, mobilfreundlichen Layouts und APIs für native Mobil-Apps.
    es_ES: CommaFeed es un lector RSS autoalojado con importación y exportación OPML, diseños adaptados a móviles y API para aplicaciones móviles nativas.
    fr_FR: CommaFeed est un lecteur RSS autohébergé avec importation et exportation OPML, des mises en page adaptées aux mobiles et des API pour applications mobiles natives.
    it_IT: CommaFeed è un lettore RSS self-hosted con importazione ed esportazione OPML, layout adatti ai dispositivi mobili e API per app mobili native.
    ja_JP: CommaFeed は、OPML のインポートとエクスポート、モバイル向けレイアウト、ネイティブモバイルアプリ向け API を備えたセルフホスト型 RSS リーダーです。
    ko_KR: CommaFeed는 OPML 가져오기/내보내기, 모바일 친화적 레이아웃, 네이티브 모바일 앱 API를 지원하는 자체 호스팅 RSS 리더입니다.
  author: CasaOS Team
  developer: CommaFeed
  category: Productivity
  version: "7.3.2"
  update_at: "2026-09-04"
  release_notes:
    en_US: Prevents users from accessing other users' starred or tagged entries.
  website: "https://www.commafeed.com/"
  repo: "https://github.com/Athou/commafeed"
  support: "https://github.com/Athou/commafeed/issues"
  docs: "https://github.com/Athou/commafeed#readme"
