name: nextcloud
services:
  nextcloud:
    image: nextcloud:33.0.3@sha256:a9e96a88c1eeec43a289e48ea4859b2e60ae4c627940ea353a034056c9def83b
    deploy:
      resources:
        reservations:
          memory: 512M
    network_mode: bridge
    ports:
    - target: 80
      published: '10081'
      protocol: tcp
    - target: 443
      published: '10443'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/var/www/html
      target: /var/www/html
    container_name: nextcloud
x-casaos:
  id: org.icewhale.nextcloud
  main: nextcloud
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.nextcloud/assets/icon.svg
  title:
    en_US: Nextcloud
  index: /
  port_map: '10081'
  version: 33.0.3
