name: v2raya
services:
  v2raya:
    image: mzz2017/v2raya:v2.2.7.5@sha256:e977dd8e332ce95ab0082e1f8f980e2dd4dd10cbb7548a2a1ff07f1d46b1b45f
    container_name: v2raya
    deploy:
      resources:
        reservations:
          memory: 128M
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
    - type: bind
      source: /lib/modules
      target: /lib/modules
      read_only: true
    - type: bind
      source: /etc/resolv.conf
      target: /etc/resolv.conf
    - type: bind
      source: /DATA/AppData/$AppID
      target: /etc/v2raya
x-casaos:
  id: org.icewhale.v2raya
  main: v2raya
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.v2raya/assets/icon.svg
  scheme: http
  port_map: '2017'
  index: /
  title:
    en_US: V2rayA
  version: 2.2.7-5
