name: vaultwarden
services:
  vaultwarden:
    image: vaultwarden/server:1.36.0@sha256:abf3d71a9c8c17c509ee55cb3fbf612f705fe868e3540a3392ccf5f371e9c6ad
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
    - target: 80
      published: '10380'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /data
    container_name: vaultwarden
x-casaos:
  app_id: org.icewhale.vaultwarden
  main: vaultwarden
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.vaultwarden/assets/icon.svg
  title:
    en_US: Vaultwarden
  index: /
  port_map: '10380'
  version: 1.36.0
