name: sure
services:
  sure-web:
    container_name: sure-web
    image: ghcr.io/we-promise/sure:0.6.5-hotfix.1
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/app/storage
      target: /rails/storage
    ports:
    - target: 3000
      published: '23000'
      protocol: tcp
    restart: unless-stopped
    environment:
      POSTGRES_USER: sure_user
      POSTGRES_PASSWORD: sure_password
      POSTGRES_DB: sure_production
      SECRET_KEY_BASE: a7523c3d0ae56415046ad8abae168d71074a79534a7062258f8d1d51ac2f76d3c3bc86d86b6b0b307df30d9a6a90a2066a3fa9e67c5e6f374dbd7dd4e0778e13
      SELF_HOSTED: 'true'
      RAILS_FORCE_SSL: 'false'
      RAILS_ASSUME_SSL: 'false'
      DB_HOST: sure-db
      DB_PORT: 5432
      REDIS_URL: redis://sure-redis:6379/1
      OPENAI_ACCESS_TOKEN: ${OPENAI_ACCESS_TOKEN}
    depends_on:
      sure-db:
        condition: service_healthy
      sure-redis:
        condition: service_healthy
    networks:
    - sure_net
    deploy:
      resources:
        reservations:
          memory: 1024M
  sure-worker:
    container_name: sure-worker
    image: ghcr.io/we-promise/sure:0.6.5-hotfix.1
    command:
    - bundle
    - exec
    - sidekiq
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/app/storage
      target: /rails/storage
    depends_on:
      sure-redis:
        condition: service_healthy
    environment:
      POSTGRES_USER: sure_user
      POSTGRES_PASSWORD: sure_password
      POSTGRES_DB: sure_production
      SECRET_KEY_BASE: a7523c3d0ae56415046ad8abae168d71074a79534a7062258f8d1d51ac2f76d3c3bc86d86b6b0b307df30d9a6a90a2066a3fa9e67c5e6f374dbd7dd4e0778e13
      SELF_HOSTED: 'true'
      RAILS_FORCE_SSL: 'false'
      RAILS_ASSUME_SSL: 'false'
      DB_HOST: sure-db
      DB_PORT: 5432
      REDIS_URL: redis://sure-redis:6379/1
      OPENAI_ACCESS_TOKEN: ${OPENAI_ACCESS_TOKEN}
    networks:
    - sure_net
    deploy:
      resources:
        reservations:
          memory: 1024M
  sure-db:
    container_name: sure-db
    image: postgres:16
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/pgdata
      target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: sure_user
      POSTGRES_PASSWORD: sure_password
      POSTGRES_DB: sure_production
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U sure_user -d sure_production
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
    - sure_net
    deploy:
      resources:
        reservations:
          memory: 1024M
  sure-redis:
    container_name: sure-redis
    image: redis:8.2.1-alpine3.22
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/redis/data
      target: /data
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
    - sure_net
    deploy:
      resources:
        reservations:
          memory: 1024M
networks:
  sure_net:
    driver: bridge
x-casaos:
  main: sure-web
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/sure/assets/icon.svg
  scheme: http
  port_map: '23000'
  index: /
  title:
    en_US: Sure
    en_GB: Sure
    it_IT: Sure
    nb_NO: Sure
    zh_CN: Sure
    ja_JP: Sure
    ko_KR: Sure
    fr_FR: Sure
    de_DE: Sure
    sv_SE: Sure
    el_GR: Sure
    hr_HR: Sure
    pt_BR: Sure
    pt_PT: Sure
    ru_RU: Sure
    tr_TR: Sure
  version: 0.6.5-hotfix.1
