name: mongodb
services:
  mongo:
    image: mongo:8.2.2@sha256:c5c7a4f391bfd632f73a7802a200c0c01ba5fb372c01ee2993bc02927cfa9158
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
    - target: 27017
      published: 27017
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/mongo/data/configdb
      target: /data/configdb
    - type: bind
      source: /DATA/AppData/mongo/data/db
      target: /data/db
    container_name: mongo
x-casaos:
  app_id: org.icewhale.mongodb
  main: mongo
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.mongodb/assets/icon.svg
  title:
    en_US: MongoDB
  version: 8.2.2
