name: medusa
services:
  medusa:
    container_name: medusa
    deploy:
      resources:
        limits:
          memory: 7848M
    environment:
    - TZ= $TZ
    image: pymedusa/medusa@sha256:c602f14ed65d70d8a8921724093290f19a6014a7e95fd37d72d83d58a19e0864
    ports:
    - target: 8081
      published: '8081'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID
      target: /config
    - type: bind
      source: /DATA/AppData/$AppID/Downloads/Television
      target: /downloads
    - type: bind
      source: /DATA/AppData/$AppID/Media/Television
      target: /tv
    network_mode: bridge
    privileged: false
x-casaos:
  app_id: org.icewhale.medusa
  main: medusa
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/medusa/assets/icon.svg
  index: /
  port_map: '8081'
  scheme: http
  title:
    en_US: Medusa
  version: 1.0.25
