name: autobrr
services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr@sha256:5b8c29a86598907496af01ec75ef21f9c0e4e28ce9d6ae6496ef91c71543ec20
    network_mode: bridge
    restart: unless-stopped
    environment:
      TZ: $TZ
    ports:
    - target: 7474
      published: '7474'
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /config
x-casaos:
  app_id: org.icewhale.autobrr
  main: autobrr
  port_map: '7474'
  title:
    en_US: Autobrr
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/autobrr/assets/icon.svg
  version: 1.79.0
