name: plex
services:
  plex:
    devices:
    - /dev/dri:/dev/dri
    - /dev/dvb:/dev/dvb
    environment:
      PGID: $PGID
      PUID: $PUID
      VERSION: docker
    image: lscr.io/linuxserver/plex:1.43.2
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: host
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /config
    - type: bind
      source: /DATA/Media
      target: /Media
    container_name: plex
x-casaos:
  id: org.icewhale.plex
  main: plex
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.plex/assets/icon.svg
  title:
    en_US: Plex
  index: /web/index.html
  port_map: '32400'
  version: 1.43.2
