name: hermes
services:
  hermes:
    image: nousresearch/hermes-agent:v2026.6.5@sha256:94da6ebb770200580d37c9f6caca70aa9c19caa252d28ac953b7cb42634728ab
    container_name: hermes
    deploy:
      resources:
        reservations:
          memory: 1G
    restart: unless-stopped
    command:
    - gateway
    - run
    ports:
    - target: 8642
      published: '8642'
      protocol: tcp
    - target: 9119
      published: '9119'
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/
      target: /opt/data
    environment:
      HERMES_DASHBOARD: 1
      HERMES_DASHBOARD_INSECURE: 1
x-casaos:
  app_id: org.icewhale.hermes
  main: hermes
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.hermes/assets/icon.svg
  scheme: http
  port_map: '9119'
  index: /
  title:
    en_US: Hermes
  version: 0.16.0
