name: pihole
services:
  pihole:
    environment:
      TZ: $TZ
      FTLCONF_webserver_api_password: casaos
      FTLCONF_dns_listeningMode: all
    image: pihole/pihole:2026.05.0
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 80
      published: '8800'
      protocol: tcp
    - target: 53
      published: '53'
      protocol: tcp
    - target: 53
      published: '53'
      protocol: udp
    - target: 443
      published: '8443'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/etc/pihole/
      target: /etc/pihole
    cap_add:
    - NET_ADMIN
    container_name: pihole
x-casaos:
  main: pihole
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/pihole/assets/icon.svg
  title:
    en_US: Pi-hole
  index: /admin
  port_map: '8800'
  version: 2026.5.0
