name: couchpotato
services:
  couchpotato:
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: $TZ
    image: linuxserver/couchpotato:version-7260c12f
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 5050
        published: "5050"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/Media/Movies
        target: /movies
      - type: bind
        source: /DATA/Downloads
        target: /downloads
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
            zh_cn: 时区
        - container: PUID
          description:
            en_us: Run CouchPotato as specified uid.
            zh_cn: 以指定的uid运行CouchPotato
        - container: PGID
          description:
            en_us: Run CouchPotato as specified gid.
            zh_cn: 以指定的gid运行CouchPotato
      index: /
      port_map: "5050"
      ports:
        - container: "5050"
          description:
            en_us: WebUI HTTP Port
            zh_cn: WebUI HTTP端口

      volumes:
        - container: /config
          description:
            en_us: CouchPotato config directory.
            zh_cn: CouchPotato配置目录
        - container: /movies
          description:
            en_us: CouchPotato movies directory.
            zh_cn: CouchPotato电影目录
        - container: /downloads
          description:
            en_us: CouchPotato downloads directory.
            zh_cn: CouchPotato下载目录
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: couchpotato
  author: CasaOS Team
  category: Media
  description:
    en_us: Awesome PVR for usenet and torrents. Just fill in what you want to see and CouchPotato will add it to your want to watch-list. Every day it will search through multiple sources, looking for the best possible match. If available, it will send it using your favorite download software.
    zh_cn: 用于usenet和torrent的优秀PVR。只需填写您想要看到的内容，CouchPotato就会将其添加到您的想要观看的列表中。每天，它都会通过多个源进行搜索，寻找最佳匹配。如果可用，它将使用您最喜欢的下载软件发送它。
    ar_sa: PVR رائع لـ usenet و torrents. ما عليك سوى ملء ما تريد مشاهدته وسيضيف CouchPotato إلى قائمة ما تريد مشاهدته. يبحث كل يوم عن مطابقة أفضل من خلال مصادر متعددة. إذا كان متاحًا ، سيقوم بإرساله باستخدام برنامج التنزيل المفضل لديك.
    de_de: Awesome PVR für usenet und torrents. Füllen Sie einfach ein, was Sie sehen möchten, und CouchPotato wird es zu Ihrer Liste hinzufügen. Jeden Tag sucht es nach mehreren Quellen, um die bestmögliche Übereinstimmung zu finden. Wenn verfügbar, sendet es es mit Ihrer bevorzugten Download-Software.
    es_es: PVR increíble para usenet y torrents. Simplemente rellene lo que desea ver y CouchPotato lo agregará a su lista de deseos. Todos los días buscará en múltiples fuentes, buscando la mejor coincidencia posible. Si está disponible, lo enviará usando su software de descarga favorito.
    fr_fr: PVR génial pour usenet et torrents. Il suffit de remplir ce que vous voulez voir et CouchPotato l'ajoutera à votre liste de souhaits. Chaque jour, il recherchera dans plusieurs sources, à la recherche de la meilleure correspondance possible. Si disponible, il l'envoie avec votre logiciel de téléchargement préféré.
    hu_hu: Awesome PVR usenet és torrentekhez. Egyszerűen töltse ki, amit látni szeretne, és a CouchPotato hozzáadja a kívánságlistájához. Mindennap keresni fog több forrásban, a lehető legjobb egyezést keresve. Ha elérhető, elküldi a kedvenc letöltőprogramjával.
    it_it: PVR fantastico per usenet e torrents. Basta compilare ciò che si desidera vedere e CouchPotato lo aggiungerà alla propria lista dei desideri. Ogni giorno cercherà in più fonti, cercando la migliore corrispondenza possibile. Se disponibile, lo invierà utilizzando il tuo software di download preferito.
    ru_ru: Awesome PVR для usenet и torrents. Просто заполните то, что вы хотите увидеть, и CouchPotato добавит его в ваш список желаний. Каждый день он будет искать в нескольких источниках, искать лучшее совпадение. Если доступно, он отправит его с помощью вашего любимого программного обеспечения для загрузки.
    pl_pl: Awesome PVR dla usenet i torrents. Wystarczy wypełnić to, co chcesz zobaczyć, a CouchPotato doda je do swojej listy życzeń. Codziennie będzie szukał w wielu źródłach, szukając najlepszego dopasowania. Jeśli jest dostępny, wyśle go za pomocą ulubionego oprogramowania do pobierania.
    pt_br: PVR incrível para usenet e torrents. Basta preencher o que você deseja ver e o CouchPotato adicionará à sua lista de desejos. Todos os dias, ele procurará em várias fontes, procurando a melhor correspondência possível. Se disponível, ele enviará usando seu software de download favorito.
    sv_se: Awesome PVR för usenet och torrents. Fyll bara i det du vill se och CouchPotato lägger till det i din önskelista. Varje dag kommer den att söka i flera källor, leta efter den bästa möjliga matchningen. Om tillgängligt kommer den att skicka det med din favorit nedladdningsprogramvara.
    uk_ua: Awesome PVR для usenet і torrents. Просто заповніть те, що ви хочете побачити, і CouchPotato додаде його до вашого списку бажань. Кожного дня він буде шукати в декількох джерелах, шукати найкраще збігання. Якщо воно доступне, він відправить його за допомогою вашого улюбленого програмного забезпечення для завантаження.
  developer: CouchPotato
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/CouchPotato/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/CouchPotato/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/CouchPotato/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/CouchPotato/screenshot-3.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/CouchPotato/screenshot-4.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/CouchPotato/screenshot-5.jpg
  tagline:
    en_us: Automatically find movies you want to watch
    zh_cn: 自动查找您想要观看的电影
    ar_sa: العثور تلقائيًا على الأفلام التي تريد مشاهدتها
    de_de: Automatisch Filme finden, die Sie sehen möchten
    es_es: Encuentra automáticamente películas que quieras ver
    fr_fr: Trouvez automatiquement des films que vous voulez voir
    hu_hu: Automatikusan találja meg a filmeket, amelyeket meg szeretne nézni
    it_it: Trova automaticamente film che vuoi vedere
    ru_ru: Автоматически находите фильмы, которые вы хотите посмотреть
    pl_pl: Automatycznie znajdź filmy, które chcesz obejrzeć  
    pt_br: Encontre automaticamente filmes que você deseja assistir
    sv_se: Hitta automatiskt filmer du vill se
    uk_ua: Автоматично знаходьте фільми, які ви хочете подивитися
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/CouchPotato/thumbnail.jpg
  tips: {}
  title:
    en_us: CouchPotato
