name: duckdns
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest@sha256:f2f40cb51dc00f27a81dc9561fe37bdd12a87fbd84a3d8135196b901f1d170bc
    container_name: duckdns
    network_mode: host
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - SUBDOMAINS=subdomain1,subdomain2
    - TOKEN=token
    - UPDATE_IP=ipv6
    - LOG_FILE=false
    volumes:
    - /DATA/AppData/duckdns:/config
    restart: unless-stopped
x-casaos:
  id: org.icewhale.duckdns
  main: duckdns
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.duckdns/assets/icon.svg
  title:
    en_US: duckdns
  index: /
  version: 0.0.1
