name: duckdns
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest@sha256:b188c998274770bbfa707d2ba50cd8eb242f9412d7959200f6c0b69a717ce8c6
    container_name: duckdns
    network_mode: host #optional
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Etc/UTC #optional
      - SUBDOMAINS=subdomain1,subdomain2
      - TOKEN=token
      - UPDATE_IP=ipv6 #optional
      - LOG_FILE=false #optional
    volumes:
      - /DATA/AppData/duckdns:/config #optional
    restart: unless-stopped

x-casaos:
  id: org.icewhale.duckdns
  main: duckdns
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.duckdns/assets/icon.svg
  title:
    en_US: duckdns
  index: /
  version: "0.0.1"
