name: etherpad
services:
  etherpad:
    image: etherpad/etherpad:3.1.0
    container_name: etherpad
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    restart: unless-stopped
    ports:
    - target: 9001
      published: '9001'
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/var
      target: /opt/etherpad-lite/var
    environment:
      TITLE: Etherpad
      DEFAULT_PAD_TEXT: 'Welcome to Etherpad on CasaOS!


        This pad text is synchronized as you type, so that everyone viewing this page
        sees the same text. This allows you to collaborate seamlessly on documents!


        Get involved with Etherpad at https://etherpad.org

        '
      ADMIN_PASSWORD: admin
      AUTHENTICATION_METHOD: apikey
      DB_TYPE: dirty
      DB_FILENAME: /opt/etherpad-lite/var/dirty.db
      TRUST_PROXY: 'true'
      SHOW_SETTINGS_IN_ADMIN_PAGE: 'true'
      REQUIRE_AUTHENTICATION: 'false'
      REQUIRE_AUTHORIZATION: 'false'
    healthcheck:
      test:
      - CMD
      - wget
      - -q
      - -O-
      - http://localhost:9001/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
x-casaos:
  app_id: org.icewhale.etherpad
  main: etherpad
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.etherpad/assets/icon.svg
  scheme: http
  port_map: '9001'
  index: /
  title:
    en_US: Etherpad
  version: 3.1.0
