name: prowlarr
services:
  prowlarr:
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/London
    image: linuxserver/prowlarr:2.3.5@sha256:5f98d030e9af715bcaac04b8ec883e5a723c40dac1f6d51d640bb6957e7990ed
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 9696
      published: '9696'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/prowlarr/config
      target: /config
    container_name: prowlarr
x-casaos:
  app_id: org.icewhale.prowlarr
  main: prowlarr
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.prowlarr/assets/icon.svg
  title:
    en_US: Prowlarr
  port_map: '9696'
  version: 2.3.5
