name: alist-sync
services:
  alist-sync:
    image: xjxjin/alist-sync:1.1.5@sha256:39a74b6305758910131f95a95077ba17963e208aedb813616fb08f07f247334d
    container_name: alist-sync
    restart: unless-stopped
    ports:
    - 52441:52441
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /app/data
    environment:
    - TZ=Asia/Shanghai
x-casaos:
  app_id: org.icewhale.alistsync
  main: alist-sync
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.alistsync/assets/icon.svg
  title:
    en_US: Alist-Sync
  port_map: '52441'
  version: 1.1.5
