name: wallabag
services:
  wallabag:
    image: wallabag/wallabag@sha256:4a527e027e0d59e87c14225ef11e005af3d4890374202ad319ce5e63dfc66709
    container_name: wallabag
    deploy:
      resources:
        reservations:
          memory: 512M
    network_mode: bridge
    ports:
    - target: 80
      published: '25661'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/images
      target: /var/www/wallabag/web/assets/images
    environment:
      SYMFONY__ENV__DOMAIN_NAME: http://<IP>:25661
      SYMFONY__ENV__SERVER_NAME: Wallabag
    healthcheck:
      test:
      - CMD
      - wget
      - --no-verbose
      - --tries=1
      - --spider
      - http://localhost/api/info
      interval: 1m
      timeout: 3s
x-casaos:
  app_id: org.icewhale.wallabag
  main: wallabag
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/wallabag/assets/icon.svg
  scheme: http
  port_map: '25661'
  index: /
  title:
    en_US: Wallabag
  version: 2.6.14
