name: archivebox
services:
  archivebox:
    image: archivebox/archivebox:0.7.4@sha256:efd1f4e2ce3459d3496bda0b8762e2ed61e8ddfb20722300382ed8804666d585
    container_name: archivebox
    deploy:
      resources:
        reservations:
          memory: 128M
    restart: unless-stopped
    networks:
    - archivebox_network
    depends_on:
    - archivebox_sonic
    ports:
    - target: 8000
      published: '18010'
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /data
    environment:
    - ADMIN_USERNAME=casaos
    - ADMIN_PASSWORD=casaos
    - ALLOWED_HOSTS=*
    - CSRF_TRUSTED_ORIGINS=*
    - PUBLIC_INDEX=True
    - PUBLIC_SNAPSHOTS=True
    - PUBLIC_ADD_VIEW=False
    - SEARCH_BACKEND_ENGINE=sonic
    - SEARCH_BACKEND_HOST_NAME=archivebox_sonic
    - SEARCH_BACKEND_PASSWORD=SomeSecretPassword
    healthcheck:
      test:
      - CMD
      - wget
      - --no-verbose
      - --tries=1
      - --spider
      - http://localhost:8000
      interval: 1m
      timeout: 3s
  archivebox_scheduler:
    image: archivebox/archivebox:0.7.4@sha256:efd1f4e2ce3459d3496bda0b8762e2ed61e8ddfb20722300382ed8804666d585
    container_name: archivebox_scheduler
    deploy:
      resources:
        reservations:
          memory: 128M
    restart: unless-stopped
    networks:
    - archivebox_network
    depends_on:
    - archivebox_sonic
    command:
    - schedule
    - --foreground
    - --update
    - --every=day
    environment:
    - TIMEOUT=120
    - SEARCH_BACKEND_ENGINE=sonic
    - SEARCH_BACKEND_HOST_NAME=archivebox_sonic
    - SEARCH_BACKEND_PASSWORD=SomeSecretPassword
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /data
  archivebox_sonic:
    image: archivebox/sonic:1.4.9@sha256:0d0767e94ccc5babb2dafd29617ae220c3432216efa218a39d73444593ebefec
    container_name: archivebox_sonic
    deploy:
      resources:
        reservations:
          memory: 128M
    restart: unless-stopped
    networks:
    - archivebox_network
    expose:
    - 1491
    environment:
    - SEARCH_BACKEND_PASSWORD=SomeSecretPassword
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/data/sonic
      target: /var/lib/sonic/store
  archivebox_novnc:
    image: theasp/novnc:latest@sha256:422644b61cf1d78a296a276f808458633c8b5a7838dbe3da1041d90a05c83e0a
    container_name: archivebox_novnc
    deploy:
      resources:
        reservations:
          memory: 128M
    restart: unless-stopped
    networks:
    - archivebox_network
    ports:
    - target: 8080
      published: '18082'
      protocol: tcp
    environment:
    - DISPLAY_WIDTH=1920
    - DISPLAY_HEIGHT=1080
    - RUN_XTERM=no
networks:
  archivebox_network:
    driver: bridge
x-casaos:
  app_id: org.icewhale.archivebox
  main: archivebox
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.archivebox/assets/icon.svg
  scheme: http
  port_map: '18010'
  index: /
  title:
    en_US: ArchiveBox
    en_GB: ArchiveBox
    it_IT: ArchiveBox
    nb_NO: ArchiveBox
    zh_CN: ArchiveBox
    ja_JP: ArchiveBox
    ko_KR: ArchiveBox
    fr_FR: ArchiveBox
    de_DE: ArchiveBox
    sv_SE: ArchiveBox
    el_GR: ArchiveBox
    hr_HR: ArchiveBox
    pt_PT: ArchiveBox
    ru_RU: ArchiveBox
    tr_TR: ArchiveBox
  version: 0.7.4
