name: sonarr
services:
  sonarr:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: linuxserver/sonarr:4.0.17@sha256:99f9ae8c01529d0c5ec6001ba79bc29182bf1e6e7cd96bb40785ba43938b8275
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
    - target: 8989
      published: '8989'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /config
    - type: bind
      source: /DATA/Media/TV Shows
      target: /tv
    - type: bind
      source: /DATA/Downloads
      target: /downloads
    container_name: sonarr
x-casaos:
  id: org.icewhale.sonarr
  main: sonarr
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.sonarr/assets/icon.svg
  title:
    en_US: Sonarr
  index: /
  port_map: '8989'
  version: 4.0.17
