name: jackett
services:
  jackett:
    environment:
      AUTO_UPDATE: 'true'
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/London
    image: linuxserver/jackett:0.24.1985@sha256:755af8eed0719de39b4030100371033162854167795594e14464603b431eb490
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 9117
      published: '9117'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /config
    - type: bind
      source: /DATA/Downloads
      target: /downloads
    container_name: jackett
x-casaos:
  app_id: org.icewhale.jackett
  main: jackett
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.jackett/assets/icon.svg
  title:
    en_US: Jackett
  index: /
  port_map: '9117'
  version: 0.24.1985
