name: pyload
services:
  pyload:
    container_name: pyload
    image: linuxserver/pyload-ng:0.5.0@sha256:2f99461c0d323aa3eec4839c7a46c44c8742307f61c3d9e3ad9c3c3c8e34af2e
    deploy:
      resources:
        reservations:
          memory: 256M
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    restart: unless-stopped
    network_mode: bridge
    privileged: false
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /config
    - type: bind
      source: /DATA/Downloads
      target: /downloads
    ports:
    - target: 8000
      published: '8000'
      protocol: tcp
    - target: 9666
      published: '9666'
      protocol: tcp
x-casaos:
  app_id: org.icewhale.pyload
  main: pyload
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.pyload/assets/icon.svg
  title:
    en_US: PyLoad
    zh_CN: PyLoad
    pt_BR: PyLoad
  index: /
  port_map: '8000'
  version: 0.5.0
