name: memos
services:
  memos:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: neosmemo/memos:0.28.0@sha256:23f7f807f8661576f8e1845e926caf48435e0826e64ded8a3d6c6ba08056f817
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 5230
      published: '5230'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/memos/memos
      target: /var/opt/memos
    container_name: memos
x-casaos:
  app_id: org.icewhale.memos
  main: memos
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.memos/assets/icon.svg
  title:
    en_US: Memos
  port_map: '5230'
  version: 0.28.0
