name: psitransfer
services:
  psitransfer:
    image: psitrax/psitransfer:v2.4.1
    container_name: psitransfer
    ports:
    - target: '3000'
      published: '13001'
      protocol: tcp
    environment:
      PSITRANSFER_ADMIN_PASS: secret
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /data
    deploy:
      resources:
        reservations:
          memory: 256M
    restart: unless-stopped
x-casaos:
  title:
    de_DE: PsiTransfer
    el_GR: PsiTransfer
    en_GB: PsiTransfer
    en_US: PsiTransfer
    fr_FR: PsiTransfer
    hr_HR: PsiTransfer
    it_IT: PsiTransfer
    ja_JP: PsiTransfer
    ko_KR: PsiTransfer
    nb_NO: PsiTransfer
    pt_PT: PsiTransfer
    ru_RU: PsiTransfer
    sv_SE: PsiTransfer
    tr_TR: PsiTransfer
    zh_CN: PsiTransfer
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/psitransfer/assets/icon.png
  index: /
  main: psitransfer
  port_map: '13001'
  scheme: http
  version: 2.4.1
