name: downtify
services:
  downtify:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: ghcr.io/henriquesebastiao/downtify:2.7.0@sha256:cac5c1536c4f1fd235d5e19b7f93dfba3e134653e3ed9c690711c8dfad8021b1
    deploy:
      resources:
        reservations:
          memory: 2048M
    ports:
    - target: 8000
      published: '8582'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/Downloads/downtify
      target: /downloads
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /data
    container_name: downtify
x-casaos:
  id: org.icewhale.downtify
  main: downtify
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.downtify/assets/icon.svg
  title:
    en_US: Downtify
  index: /
  port_map: '8582'
  version: 2.7.0
