name: deluge
services:
  deluge:
    environment:
      DELUGE_LOGLEVEL: error
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: linuxserver/deluge:2.1.1
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
      - target: 8112
        published: "8112"
        protocol: tcp
      - target: 6881
        published: "6881"
        protocol: tcp
      - target: 6881
        published: "6881"
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA
        target: /DATA
    x-casaos:
      author: CasaOS Team
      category: Downloader
      container:
        envs:
          - container: TZ
            description:
              en_US: TimeZone
              zh_CN: 时区
          - container: PUID
            description:
              en_US: Run Deluge as specified uid.
              zh_CN: 以指定的 uid 运行 Deluge。
          - container: PGID
            description:
              en_US: Run Deluge as specified gid.
              zh_CN: 以指定的 gid 运行 Deluge。
          - container: DELUGE_LOGLEVEL
            description:
              en_US: Deluge Log Level
              zh_CN: Deluge 日志级别
        index: /
        port_map: "8112"
        ports:
          - container: "8112"
            description:
              en_US: WebUI HTTP Port
              zh_CN: WebUI HTTP 端口

          - container: "6881"
            description:
              en_US: Inbound torrent traffic (TCP)
              zh_CN: 入站 torrent 流量（TCP）

          - container: "6881"
            description:
              en_US: Inbound torrent traffic (UDP)
              zh_CN: 入站 torrent 流量（UDP）
            protocol: udp

        volumes:
          - container: /config
            description:
              en_US: Deluge config directory.
              zh_CN: Deluge 配置目录。
          - container: /DATA
            description:
              en_US: Deluge Accessible directory.
              zh_CN: Deluge 可访问目录。
      description:
        en_US: Deluge contains the common features to BitTorrent clients such as Protocol Encryption, DHT, Local Peer Discovery (LSD), Peer Exchange (PEX), UPnP, NAT-PMP, Proxy support, Web seeds, global and per-torrent speed limits. As Deluge heavily utilises the ​libtorrent library it has a comprehensive list of the ​features provided.
        zh_CN: Deluge 包含 BitTorrent 客户端的常见功能，如协议加密、DHT、本地对等发现（LSD）、对等交换（PEX）、UPnP、NAT-PMP、代理支持、Web 种子、全局和每个 torrent 速度限制。由于 Deluge 大量利用了 libtorrent 库，因此它具有提供的功能的详细列表。
      developer: Deluge Team
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Deluge/icon.png
      screenshot_link:
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Deluge/screenshot-1.jpg
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Deluge/screenshot-2.jpg
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Deluge/screenshot-3.jpg
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Deluge/screenshot-4.jpg
      tagline:
        en_US: A lightweight and free BitTorrent client.
        zh_CN: 轻量级且免费的 BitTorrent 客户端。
      thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Deluge/thumbnail.jpg
      tips:
        before_install:
          en_US: |
            Default Password: `deluge`

            Default Accessible Path in Deluge

            | Name | Value |
            | --- | --- |
            | DATA Path | `/DATA` |
            | Downloads Path | `/DATA/Downloads` |
            | Media Path | `/DATA/Media` |

            The paths of other DATA subdirectories in CasaOS are also similar.

            Please make sure you use the correct path when using Deluge.
          zh_CN: |
            默认密码：`deluge`

            Deluge 中可访问的路径

            | 名称 | 值 |
            | --- | --- |
            | DATA 路径 | `/DATA` |
            | 下载路径 | `/DATA/Downloads` |
            | 媒体路径 | `/DATA/Media` |

            CasaOS 中其他 DATA 子目录的路径也类似。

            请确保在使用 Deluge 时使用正确的路径。
      title:
        en_US: Deluge
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main_app: deluge
