name: homeassistant
services:
  homeassistant:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: homeassistant/home-assistant@sha256:ceb1202133a5a036e8b03e20a10eb113186cc2f871968323c6fc6c3fc4205716
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: host
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /config
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
    - type: bind
      source: /run/dbus
      target: /run/dbus
      read_only: true
    privileged: true
    container_name: homeassistant
x-casaos:
  app_id: org.icewhale.homeassistant
  main: homeassistant
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/homeassistant/assets/icon.svg
  title:
    en_US: Home Assistant
  index: /
  port_map: '8123'
  version: 2026.5.4
