name: netdata
services:
  app:
    cap_add:
    - SYS_PTRACE
    - SYS_ADMIN
    cpu_shares: 90
    container_name: netdata
    deploy:
      resources:
        limits:
          memory: 1794M
    image: netdata/netdata:v2.10.3
    pid: host
    ports:
    - target: 19999
      published: '19999'
      protocol: tcp
    restart: unless-stopped
    security_opt:
    - apparmor:unconfined
    volumes:
    - type: bind
      source: /DATA/AppData/Netdata/config
      target: /etc/netdata
    - type: bind
      source: /DATA/AppData/Netdata/lib
      target: /var/lib/netdata
    - type: bind
      source: /DATA/AppData/Netdata/cache
      target: /var/cache/netdata
    - type: bind
      source: /etc/passwd
      target: /host/etc/passwd
    - type: bind
      source: /etc/group
      target: /host/etc/group
    - type: bind
      source: /proc
      target: /host/proc
    - type: bind
      source: /sys
      target: /host/sys
    - type: bind
      source: /etc/os-release
      target: /host/etc/os-release
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    network_mode: bridge
    privileged: false
x-casaos:
  app_id: com.icewhaletech.netdata
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/netdata/assets/icon.svg
  index: /
  port_map: '19999'
  scheme: http
  title:
    en_US: Netdata
  version: 2.10.3
