---
name: netdata
services:
  app:
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    cpu_shares: 90
    container_name: netdata
    deploy:
      resources:
        limits:
          memory: 1794M
    image: netdata/netdata:stable
    labels:
      icon: https://icon.casaos.io/main/all/netdata.png
    pid: host
    ports:
      - target: 19999
        published: "19999"
        protocol: tcp
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    volumes:
      - type: bind
        source: /DATA/AppData/Netdata/config
        target: /etc/netdata
      - type: bind
        source: /DATA/AppData/Netdata/lib
        target: /var/lib/netdata
      - type: bind
        source: /DATA/AppData/Netdata/cache
        target: /var/cache/netdata
      - type: bind
        source: /etc/passwd
        target: /host/etc/passwd
      - type: bind
        source: /etc/group
        target: /host/etc/group
      - type: bind
        source: /proc
        target: /host/proc
      - type: bind
        source: /sys
        target: /host/sys
      - type: bind
        source: /etc/os-release
        target: /host/etc/os-release
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    network_mode: bridge
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  author: f4bio
  category: Utilities
  description:
    en_us: Netdata is a real-time performance and health monitoring solution that helps you visualize and understand the behavior of your systems.
    zh_cn: Netdata是一个实时性能和健康监控解决方案，帮助您可视化并理解系统的行为。
  tagline:
    en_us: Real-time Performance Monitoring
    zh_cn: 实时性能监控
  hostname: ""
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Netdata/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Netdata/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Netdata/screenshot-3.png
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Netdata/icon.png
  index: /
  port_map: "19999"
  scheme: http
  store_app_id: netdata
  title:
    en_us: Netdata
