name: holoplay
services:
  holoplay:
    image: spout8301/holoplay@sha256:76531b11df9f093f5c1ec86d59db7a19a9dee09cad03467eda207987d14e7d64
    ports:
    - target: 3000
      published: '3000'
      protocol: tcp
    privileged: true
    restart: unless-stopped
    container_name: holoplay
x-casaos:
  app_id: org.icewhale.holoplay
  main: holoplay
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/holoplay/assets/icon.svg
  title:
    en_US: HoloPlay
  index: /
  port_map: '3000'
  version: 1.12.3
