version: '3'
name: firefly
services:
  firefly:
    image: uusec/firefly:latest@sha256:301c987a2365082f94e55874c28b829fc6032e37b67710c8fc4b527f73daeab4
    container_name: firefly
    devices:
    - /dev/net/tun:/dev/net/tun
    network_mode: host
    volumes:
    - /lib/modules:/lib/modules
    - /DATA/AppData/firefly/conf:/firefly/conf
    cap_add:
    - NET_ADMIN
    - SYS_MODULE
    restart: unless-stopped
    environment:
    - FIREFLY_PASSWORD=firefly
    deploy:
      resources:
        reservations:
          memory: 32M
x-casaos:
  app_id: org.icewhale.firefly
  main: firefly
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.firefly/assets/icon.svg
  title:
    en_US: Firefly
    zh_CN: 萤火虫
  port_map: '50121'
  scheme: http
  index: /
  version: 0.0.1
