name: ddns-updater
services:
  ddns-updater:
    image: qmcgaw/ddns-updater:v2.6.0
    network_mode: bridge
    command:
      - touch /data/config.json
    container_name: ddns-updater
    deploy:
      resources:
        limits:
          memory: 32M
    environment:
      - BACKUP_DIRECTORY=/updater/data
      - BACKUP_PERIOD=0
      - CONFIG=
      - HTTP_TIMEOUT=10s
      - LISTENING_ADDRESS=:8000
      - LOG_CALLER=hidden
      - LOG_LEVEL=info
      - PERIOD=5m
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - ROOT_URL=/
      - SHOUTRRR_ADDRESSES=
      - UPDATE_COOLDOWN_PERIOD=5m
    hostname: ddns-updater
    ports:
      - target: 8000
        published: "8000"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /updater/data
    x-casaos:
      ports:
        - container: "8000"
          description:
            en_us: WebUI HTTP Port
      volumes:
        - container: /updater/data
          description:
            en_us: ddns-updater config directory.
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: rstuhlmuller
  category: Network
  description:
    en_us: Program to keep DNS A and/or AAAA records updated for multiple DNS providers
  developer: qmcgaw
  screenshot:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/DDNS-Updater/screenshot-1.png
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/DDNS-Updater/icon.png
  main: ddns-updater
  port_map: "8000"
  scheme: http
  tagline:
    en_us: Simple and easy to use DDNS
    zh_cn: 简单好用的DDNS
  title:
    en_us: ddns-updater
