name: duckdns
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns@sha256:424dbc5a5db5388ad4c197882eac475c5bfad2be1e02a761692946d406591b17
    container_name: duckdns
    network_mode: host
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - SUBDOMAINS=subdomain1,subdomain2
    - TOKEN=token
    - UPDATE_IP=ipv6
    - LOG_FILE=false
    volumes:
    - /DATA/AppData/duckdns:/config
    restart: unless-stopped
x-casaos:
  app_id: com.icewhaletech.duckdns
  main: duckdns
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/duckdns/assets/icon.svg
  title:
    en_US: duckdns
  index: /
  version: 0.0.1
