name: duckdns
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host #optional
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Etc/UTC #optional
      - SUBDOMAINS=subdomain1,subdomain2
      - TOKEN=token
      - UPDATE_IP=ipv6 #optional
      - LOG_FILE=false #optional
    volumes:
      - /DATA/AppData/duckdns:/config #optional
    restart: unless-stopped

x-casaos:
  architectures:
    - amd64
    - arm64
  main: duckdns
  author: DuckDNS Team
  category: Utilities
  description:
    en_us: duckdns is a DDNS (Dynamic DNS) application that dynamically binds IP addresses to domain names, supporting both IPv4 and IPv6.
    zh_cn: duckdns是一个DDNS（动态DNS）应用，能够动态地将IP地址绑定到域名，支持IPv4和IPv6。
    ar_sa: duckdns هو تطبيق DDNS (نظام أسماء النطاقات الديناميكي) يربط عناوين IP بالأسماء المجالية ديناميكيًا، ويدعم كلاً من IPv4 و IPv6.
    de_de: duckdns ist eine DDNS (Dynamic DNS)-Anwendung, die IP-Adressen dynamisch an Domainnamen bindet und sowohl IPv4 als auch IPv6 unterstützt.
    es_es: duckdns es una aplicación DDNS (DNS dinámico) que vincula dinámicamente direcciones IP a nombres de dominio, compatible con IPv4 e IPv6.
    fr_fr: duckdns est une application DDNS (DNS dynamique) qui lie dynamiquement des adresses IP à des noms de domaine, prenant en charge IPv4 et IPv6.
    hu_hu: A duckdns egy DDNS (dinamikus DNS) alkalmazás, amely dinamikusan köti az IP-címeket a domainnevekhez, és támogatja az IPv4 és IPv6 protokollokat.
    it_it: duckdns è un'applicazione DDNS (DNS dinamico) che lega dinamicamente gli indirizzi IP ai nomi di dominio, supportando sia IPv4 che IPv6.
    ru_ru: duckdns - это приложение DDNS (динамический DNS), которое динамически связывает IP-адреса с доменными именами, поддерживая как IPv4, так и IPv6.
    pl_pl: duckdns to aplikacja DDNS (dynamiczny DNS), która dynamicznie wiąże adresy IP z nazwami domen, obsługując zarówno IPv4, jak i IPv6.
    pt_br: duckdns é um aplicativo DDNS (DNS dinâmico) que vincula dinamicamente endereços IP a nomes de domínio, suportando IPv4 e IPv6.
    sv_se: duckdns är en DDNS (dynamisk DNS)-applikation som dynamiskt binder IP-adresser till domännamn och stöder både IPv4 och IPv6.
    uk_ua: duckdns - це програма DDNS (динамічний DNS), яка динамічно прив'язує IP-адреси до доменних імен, підтримуючи як IPv4, так і IPv6.
  developer: DuckDNS Team
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/DuckDNS/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/DuckDNS/screenshot-1.png
  tagline:
    en_us: Dynamic DNS for your domain, supporting both IPv4 and IPv6
    zh_cn: 为您的域名提供动态DNS服务，支持IPv4和IPv6
    ar_sa: DNS ديناميكي لنطاقك، يدعم كلاً من IPv4 و IPv6
    de_de: Dynamisches DNS für Ihre Domain, unterstützt sowohl IPv4 als auch IPv6
    es_es: DNS dinámico para su dominio, compatible con IPv4 e IPv6
    fr_fr: DNS dynamique pour votre domaine, prenant en charge IPv4 et IPv6
    hu_hu: Dinamikus DNS a domainjéhez, támogatja az IPv4 és IPv6 protokollokat
    it_it: DNS dinamico per il tuo dominio, supporta sia IPv4 che IPv6
    ru_ru: Динамический DNS для вашего домена, поддерживает как IPv4, так и IPv6
    pl_pl: Dynamiczny DNS dla Twojej domeny, obsługujący zarówno IPv4, jak i IPv6
    pt_br: DNS dinâmico para seu domínio, suportando IPv4 e IPv6
    sv_se: Dynamisk DNS för din domän, stöder både IPv4 och IPv6
    uk_ua: Динамічний DNS для вашого домену, підтримує як IPv4, так і IPv6
  tips:
    before_install:
      en_us: |
        Attention Please
        Will update IPv6 address by default. You can modify it by settings.

        Please register sub-domain on https://www.duckdns.org/ and gain your token.

      zh_cn: |
        请注意
        将默认更新IPv6，你可以在设置面板更改。

        请在https://www.duckdns.org/注册子域名并获取token。

  title:
    en_us: duckdns
  index: /