name: esphome
services:
  esphome:
    container_name: esphome
    deploy:
      resources:
        reservations:
          memory: 512M
    image: ghcr.io/esphome/esphome:2026.5.1
    restart: always
    ports:
    - target: 6052
      published: '6052'
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /config
    environment:
      ESPHOME_DASHBOARD_USE_PING: 'false'
      TZ: $TZ
    network_mode: host
    privileged: false
x-casaos:
  app_id: com.icewhaletech.esphome
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/esphome/assets/icon.svg
  index: /
  main: esphome
  port_map: '6052'
  scheme: http
  title:
    en_US: ESPHome
  version: 2026.5.1
