name: moviepilot
services:
    moviepilot:
        stdin_open: true
        tty: true
        container_name: moviepilot
        hostname: moviepilot
        network_mode: host
        ports:
            - target: 3000
              published: 3000
              protocol: tcp
        volumes:
            - '/DATA/Media:/media'
            - '/DATA/AppData/$AppID/moviepilot/config:/config'
            - '/DATA/AppData/$AppID/moviepilot/core:/moviepilot/.cache/ms-playwright'
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
        environment:
            - 'NGINX_PORT=3000'
            - 'PORT=3001'
            - 'AUTH_SITE=iyuu'
            - 'IYUU_SIGN=xxxx'
            - 'SUPERUSER=admin'
            - 'API_TOKEN=moviepilot'
        restart: always
        image: jxxghp/moviepilot:latest
x-casaos:
    architectures:
        - amd64
    author: CasaOS Team
    category: Media
    developer: unknown
    tagline:
      en_us: Video Management
      zh_cn: 视频管理
    title:
      en_us: Movie Pilot
      pt_br: Movie Pilot
    icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/MoviePilot/icon.png
    main: moviepilot
    port_map: "3000"