name: actualbudget
services:
  actualbudget:
    image: actualbudget/actual-server@sha256:1aeeb3985db55556e716dec25e08f6ce09308c2571b65cddbc6746ee6d5e0d45
    container_name: actualbudget
    deploy:
      resources:
        reservations:
          memory: 128M
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID
      target: /data
    ports:
    - target: 5006
      published: '15006'
      protocol: tcp
x-casaos:
  app_id: org.icewhale.actualbudget
  main: actualbudget
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/actualbudget/assets/icon.svg
  scheme: http
  port_map: '15006'
  index: /
  title:
    en_US: Actual Budget
  version: 26.5.2
