name: medusa
services:
  medusa:
    container_name: medusa
    deploy:
      resources:
        limits:
          memory: 7848M
    environment:
    - TZ= $TZ
    image: pymedusa/medusa:master@sha256:db6cde59a29958515a601420b75c38bf7b26ba0b614d27078f52f49bfeaba03d
    ports:
    - target: 8081
      published: '8081'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID
      target: /config
    - type: bind
      source: /DATA/AppData/$AppID/Downloads/Television
      target: /downloads
    - type: bind
      source: /DATA/AppData/$AppID/Media/Television
      target: /tv
    network_mode: bridge
    privileged: false
x-casaos:
  id: org.icewhale.medusa
  main: medusa
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.medusa/assets/icon.svg
  index: /
  port_map: '8081'
  scheme: http
  title:
    en_US: Medusa
  version: 1.0.25
