name: gateway-go
services:
  gateway-go:
    image: openiothub/gateway-go:v2.0.12@sha256:e5610b323604c4cb638090e488e2a6472ce188feff53f6a6cfa89d31f519dc2d
    network_mode: host
    deploy:
      resources:
        reservations:
          memory: 32M
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /root
    ports:
    - target: 34323
      published: '34323'
      protocol: tcp
    container_name: gateway-go
x-casaos:
  id: org.icewhale.gatewaygo
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.gatewaygo/assets/icon.svg
  main: gateway-go
  port_map: '34323'
  scheme: http
  title:
    en_US: gateway-go
  version: 2.0.12
