name: photoprism
services:
  photoprism:
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: casaos
      PHOTOPRISM_UPLOAD_NSFW: 'true'
      TZ: $TZ
    image: photoprism/photoprism@sha256:ee3d15cf76f80c2fb4a28c336a63173b0c671ed7a3dd9ec0ed6231b7defa8876
    deploy:
      resources:
        reservations:
          memory: 512M
    network_mode: bridge
    ports:
    - target: 2342
      published: '2342'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/photoprism/storage
      target: /photoprism/storage
    - type: bind
      source: /DATA/Gallery
      target: /photoprism/originals
    container_name: photoprism
x-casaos:
  app_id: org.icewhale.photoprism
  main: photoprism
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/photoprism/assets/icon.svg
  title:
    en_US: PhotoPrism
  index: /
  port_map: '2342'
  version: 260523.0.0
