name: actualbudget
services:
  actualbudget:
    image: actualbudget/actual-server:26.5.2@sha256:5b7c25a606c6efed6f73642c7c3459233d189eee940efecb627a063eecf6b494
    container_name: actualbudget
    deploy:
      resources:
        reservations:
          memory: 128M
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID
      target: /data
    ports:
    - target: 5006
      published: '15006'
      protocol: tcp
x-casaos:
  id: org.icewhale.actualbudget
  main: actualbudget
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.actualbudget/assets/icon.svg
  scheme: http
  port_map: '15006'
  index: /
  title:
    en_US: Actual Budget
  version: 26.5.2
