name: databag
services:
  databag:
    image: balzack/databag:0.1.18@sha256:1e36d8e969607de328a412a5820982e8ed7eb02afea5bdabd160abeef87fdbd5
    restart: unless-stopped
    ports:
    - target: 7000
      published: 7000
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/databag/data
      target: /var/lib/databag
    container_name: databag
x-casaos:
  id: org.icewhale.databag
  main: databag
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.databag/assets/icon.svg
  title:
    en_US: Databag
  port_map: '7000'
  version: 0.1.18
