name: media-fetch-pro
services:
  media-fetch-pro:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: correctroad/media-fetch-pro:0.3.2
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 7789
        published: "7789"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/Media/MediaFetchPro
        target: /var/opt/video
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /var/opt/config

    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: "timezone"
            zh_cn: "时区"
      ports:
        - container: "7789"
          description:
            en_us: WebUI HTTP Port
            zh_cn: WebUI HTTP 端口
      volumes:
        - container: /var/opt/video
          description:
            en_us: video download directory.
            zh_cn: 视频下载目录
    container_name: mediafetchpro
x-casaos:
  architectures:
    - amd64
    - arm64
  main: media-fetch-pro
  author: CorrectRoadH
  category: Media
  description:
    en_us: Media Fetch PRO is an application to download video of youtube, bilibili and more websites in future with metadata to jellyfin, emby, plex and more softwares in future. Project - https://github.com/Media-Fetch-Pro/Media-Fetch-Pro
    zh_cn: Media Fetch PRO 可以从 Bilibili、Youtube等网站下载带有刮削的视频到 Jellyfin、Emby、Plex等软件组成好看的海报墙。项目地址 - https://github.com/Media-Fetch-Pro/Media-Fetch-Pro
  developer: CorrectRoadH
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/MediaFetchPro/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/MediaFetchPro/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/MediaFetchPro/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/MediaFetchPro/screenshot-3.png
  tagline:
    en_us: Media Fetch PRO is an application to download video of youtube, bilibili and more websites in future with metadata to jellyfin, emby, plex and more softwares in future.
    zh_cn: Media Fetch PRO 可以从 Bilibili、Youtube等网站下载带有刮削的视频到 Jellyfin、Emby、Plex等软件组成好看的海报墙。
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/MediaFetchPro/thumbnail.png
  tips: 
    before_install:
        en_us: Media Fetch PRO is in beta test yet. So you may lose your download history in the future and you may got some bugs.
        zh_cn: Media Fetch PRO 还在 beta 测试中，所以您可能在未来升级后会丢失你的下载记录并且会在使用中遇到很多 bug。
  title:
    en_us: Media Fetch Pro
  port_map: "7789"
