name: label-studio
services:
  label-studio:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: heartexlabs/label-studio@sha256:aa461572e8f9d86a1bf9520c1db620204e86160fd2f80dd7e9d40ac84a8828ea
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
    - target: 8080
      published: '3080'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /label-studio/data
x-casaos:
  app_id: org.icewhale.labelstudio
  main: label-studio
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/label-studio/assets/icon.svg
  title:
    en_US: Label Studio
  port_map: '3080'
  version: 1.23.0
