name: openhands
services:
  openhands:
    image: ghcr.io/all-hands-ai/openhands:0.59
    container_name: openhands
    environment:
    - SANDBOX_RUNTIME_CONTAINER_IMAGE=ghcr.io/all-hands-ai/runtime:main-nikolaik
    - WORKSPACE_MOUNT_PATH=/DATA/AppData/$AppID/workspace
    ports:
    - 13333:3000
    extra_hosts:
    - host.docker.internal:host-gateway
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /DATA/AppData/$AppID/openhands:/.openhands
    - /DATA/AppData/$AppID/workspace:/opt/workspace_base
    stdin_open: true
    tty: true
x-casaos:
  app_id: org.icewhale.openhands
  main: openhands
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/openhands/assets/icon.svg
  scheme: http
  port_map: '13333'
  index: /
  title:
    en_US: OpenHands
    en_GB: OpenHands
    it_IT: OpenHands
    nb_NO: OpenHands
    zh_CN: OpenHands
    ja_JP: OpenHands
    ko_KR: OpenHands
    fr_FR: OpenHands
    de_DE: OpenHands
    sv_SE: OpenHands
    el_GR: OpenHands
    hr_HR: OpenHands
    pt_PT: OpenHands
    ru_RU: OpenHands
    tr_TR: OpenHands
  version: 0.59.0
