name: deepseek-ocr-nvidia
services:
  deepseek-ocr-backend:
    image: icewhaletech/deepseek-ocr-backend:v2.2.0
    container_name: deepseek-ocr-backend
    environment:
      API_HOST: 0.0.0.0
      API_PORT: '8000'
      FRONTEND_PORT: '3000'
      MODEL_NAME: deepseek-ai/DeepSeek-OCR
      HF_HOME: /models
      MAX_UPLOAD_SIZE_MB: '100'
      BASE_SIZE: '1024'
      IMAGE_SIZE: '640'
      CROP_MODE: 'true'
    volumes:
    - /DATA/AppData/$AppID/models:/models
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities:
            - gpu
          memory: 8G
    shm_size: 4g
    ports:
    - target: 8000
      published: '22523'
      protocol: tcp
    networks:
    - deepseek-ocr-network
  deepseek-ocr-frontend:
    image: icewhaletech/deepseek-ocr-frontend:v2.2.0
    container_name: deepseek-ocr-frontend
    ports:
    - target: 80
      published: '23000'
      protocol: tcp
    deploy:
      resources:
        reservations:
          memory: 512M
    depends_on:
    - deepseek-ocr-backend
    networks:
    - deepseek-ocr-network
networks:
  deepseek-ocr-network:
    driver: bridge
x-casaos:
  app_id: com.icewhaletech.deepseekocrnvidia
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/deepseek-ocr-nvidia/assets/icon.svg
  index: /
  main: deepseek-ocr-frontend
  port_map: '23000'
  scheme: http
  title:
    de_DE: DeepSeek OCR(Nvidia GPU)
    el_GR: DeepSeek OCR(Nvidia GPU)
    en_GB: DeepSeek OCR(Nvidia GPU)
    en_US: DeepSeek OCR(Nvidia GPU)
    fr_FR: DeepSeek OCR(Nvidia GPU)
    hr_HR: DeepSeek OCR(Nvidia GPU)
    it_IT: DeepSeek OCR(Nvidia GPU)
    ja_JP: DeepSeek OCR(Nvidia GPU)
    ko_KR: DeepSeek OCR(Nvidia GPU)
    nb_NO: DeepSeek OCR(Nvidia GPU)
    pt_PT: DeepSeek OCR(Nvidia GPU)
    ru_RU: DeepSeek OCR(Nvidia GPU)
    sv_SE: DeepSeek OCR(Nvidia GPU)
    tr_TR: DeepSeek OCR(Nvidia GPU)
    zh_CN: DeepSeek OCR(Nvidia GPU)
  version: 2.2.0
