name: netbird
services:
  netbird:
    image: netbirdio/netbird:0.62.3
    container_name: netbird
    network_mode: host
    restart: unless-stopped
    cap_add:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
    deploy:
      resources:
        reservations:
          memory: 128M
    environment:
      NB_SETUP_KEY: ''
      NB_MANAGEMENT_URL: ''
      NB_HOSTNAME: Zima
      NB_ENABLE_SSH_ROOT: 'true'
      NB_ALLOW_SERVER_SSH: 'true'
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID
      target: /var/lib/netbird
x-casaos:
  app_id: org.icewhale.netbird
  main: netbird
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/netbird/assets/icon.svg
  scheme: https
  port_map: ''
  index: /
  title:
    en_US: NetBird
  version: 0.62.3
