name: langflow
services:
  langflow:
    container_name: langflow
    image: langflowai/langflow:1.9.3
    user: 0:0
    ports:
    - target: 7860
      published: '17860'
      protocol: tcp
    depends_on:
    - langflow-postgres
    networks:
    - langflow-net
    environment:
    - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@langflow-postgres:5432/langflow
    - LANGFLOW_CONFIG_DIR=/app/langflow
    volumes:
    - /DATA/AppData/$AppID/backend:/app/langflow
  langflow-postgres:
    container_name: langflow-postgress
    image: postgres:16
    environment:
    - POSTGRES_USER=langflow
    - POSTGRES_PASSWORD=langflow
    - POSTGRES_DB=langflow
    networks:
    - langflow-net
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/postgres
      target: /var/lib/postgresql/data
networks:
  langflow-net:
    driver: bridge
x-casaos:
  id: org.icewhale.langflow
  main: langflow
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.langflow/assets/icon.svg
  scheme: http
  port_map: '17860'
  index: /
  title:
    en_US: Langflow
    en_GB: Langflow
    it_IT: Langflow
    nb_NO: Langflow
    zh_CN: Langflow
    ja_JP: Langflow
    ko_KR: Langflow
    fr_FR: Langflow
    de_DE: Langflow
    sv_SE: Langflow
    el_GR: Langflow
    hr_HR: Langflow
    pt_PT: Langflow
    ru_RU: Langflow
    tr_TR: Langflow
  version: 1.9.3
