name: netronome

services:
  netronome:
    image: ghcr.io/autobrr/netronome:v0.13.0@sha256:22497d1597541bbeac6a635a01918b90d93c5e98d0b2587c37a5205b182cac94
    container_name: netronome
    restart: unless-stopped
    entrypoint:
      - /sbin/tini
      - --
      - /bin/sh
      - -c
    command:
      - |-
        config=/data/.config/netronome/config.toml
        if [ ! -f "$$config" ]; then
          netronome generate-config
        fi
        exec netronome serve
    ports:
      - target: 7575
        published: "7575"
        protocol: tcp
    environment:
      TZ: $TZ
      NETRONOME__HOST: 0.0.0.0
      NETRONOME__PORT: 7575
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
    cap_add:
      - NET_RAW
x-casaos:
  id: org.icewhale.netronome
  main: netronome
  index: /
  port_map: "7575"
  scheme: http
  title:
    en_US: Netronome
    zh_CN: Netronome
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.netronome/assets/icon.png
  version: "0.13.0"
