name: validate docker compose file

on:
    pull_request:
      types: [opened, synchronize]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: houqp/download-release-assets@v1
        with:
          repo: IceWhaleTech/CasaOS-AppManagement
          match: "linux-amd64-casaos-app-management-validator-.+.tar.gz$"
          rename: validator.tar.gz
    
      - name: Extract
        run: |
            tar -zxvf validator.tar.gz /
            chmod +x /usr/local/bin/casaos-app-management-validator

      - name: Check name field in YAML files
        id: validate_docker_compose
        run: |

            find . -type f \( -name "docker-compose.yaml" -or -name "docker-compose.yml" \) | while read -r file; do
                /usr/local/bin/casaos-app-management-validator $file
            done
