name: validate docker compose file

on:
    pull_request:
      types: [opened, synchronize]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - uses: robinraju/release-downloader@v1.9
        with:
          repository: "IceWhaleTech/CasaOS-AppManagement"
          latest: true
          fileName: "linux-amd64-casaos-app-management-validator-*.tar.gz"

      - name: Extract
        run: |
            tar zxf linux-amd64-casaos-app-management-validator-*.tar.gz

      - name: Install
        run: |
            chmod +x build/sysroot/usr/bin/casaos-app-management-validator

      - name: Check All Docker Compose File
        id: validate_docker_compose
        run: |
            find . -type f \( -name "docker-compose.yaml" -or -name "docker-compose.yml" \) | while read -r file; do
              echo $file
              build/sysroot/usr/bin/casaos-app-management-validator $file
            done
