name: gitea
services:
  gitea:
    environment:
      USER_GID: '1000'
      USER_UID: '1000'
    image: gitea/gitea@sha256:7d13848af12645600a5f9d93ee2560daa9c6fa6b5b859b7bff3a5e1c0b661031
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
    - target: 3000
      published: '3002'
      protocol: tcp
    - target: 22
      published: '222'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /data
    container_name: gitea
x-casaos:
  app_id: org.icewhale.gitea
  main: gitea
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/gitea/assets/icon.svg
  title:
    en_US: Gitea
  index: /
  port_map: '3002'
  version: 1.26.2
