name: lucky
services:
  lucky:
    deploy:
      resources:
        reservations:
          memory: 64M
    image: gdy666/lucky:2.27.2@sha256:6bf725aaca3e866cc6dd71f8a5ce30018db35e763b7655287f2ce598d986e455
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/lucky
      target: /goodluck
    environment:
      TZ: $TZ
    network_mode: host
    privileged: false
x-casaos:
  app_id: org.icewhale.lucky
  main: lucky
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.lucky/assets/icon.svg
  index: /
  title:
    en_US: Lucky
  port_map: '16601'
  scheme: http
  version: 2.27.2
