name: ombi
services:
  ombi:
    environment:
      BASE_URL: /ombi
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/London
    image: linuxserver/ombi:4.53.5@sha256:9d5f932a6bf5ddb8dca396b71922381457e8d2d0534364fd6bf05034a27c0a92
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 3579
      published: '3579'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/ombi/config
      target: /config
    container_name: ombi
x-casaos:
  id: org.icewhale.ombi
  main: ombi
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.ombi/assets/icon.svg
  title:
    en_US: Ombi
  port_map: '3579'
  version: 4.53.5
